# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '7a25ce852919b2f2fb462549704c207c0fd8e426e56ad5351551dd454296b1a0'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack