# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.fgii_graham.root] run return 0
execute on passengers if entity @s[tag=aj.fgii_graham.data] unless data entity @s {data:{rigHash: '90b1851a69ccb34027aaa5378ed8365b0e1575ea97594c3aca1bd95445b90c07'}} on vehicle run function animated_java:fgii_graham/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1