# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.fgii_graham.root] run return 0
execute on passengers if entity @s[tag=aj.fgii_graham.data] unless data entity @s {data:{rigHash: 'd3f2dbfe2506225631bf6ffded6e8ff61b7458f9e8b10fdfd3b2fd13e048ffed'}} on vehicle run function animated_java:fgii_graham/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1