# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.sudowoodo.root] run return 0
execute if entity @s[tag=aj.sudowoodo.animation.ground_idle.playing] run function animated_java:sudowoodo/animations/ground_idle/zzz/on_tick
execute if entity @s[tag=aj.sudowoodo.animation.animation_sudowoodo_blink.playing] run function animated_java:sudowoodo/animations/animation_sudowoodo_blink/zzz/on_tick
execute if entity @s[tag=aj.sudowoodo.animation.animation_sudowoodo_cry.playing] run function animated_java:sudowoodo/animations/animation_sudowoodo_cry/zzz/on_tick