# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.shell2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_shell2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.shell] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_shell set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.pupil_right2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_pupil_right2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.pupil_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_pupil_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.eyelid_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_eyelid_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.eye_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_eye_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.pupil_left2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_pupil_left2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.pupil_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_pupil_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.eyelid_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_eyelid_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.eye_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_eye_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.muzzle2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_muzzle2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.muzzle] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_muzzle set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.tongue] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tongue set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.jaw] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_jaw set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.ear_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.ear_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.head_angle] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head_angle set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.neck3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.neck2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.chest2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chest2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.chest] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chest set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.tail2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.tail] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.torso] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_torso set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.leg_front_left4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_front_left4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.leg_front_left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_front_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.leg_front_left2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_front_left2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.leg_front_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_front_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.leg_back_left4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_back_left4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.leg_back_left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_back_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.leg_back_left2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_back_left2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.leg_back_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_back_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.leg_front_right4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_front_right4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.leg_front_right3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_front_right3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.leg_front_right2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_front_right2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.leg_front_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_front_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.leg_back_right4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_back_right4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.leg_back_right3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_back_right3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.leg_back_right2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_back_right2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.bone.leg_back_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_back_right set from storage aj:uuid main.out