# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.lapras.root] run return 0
execute if entity @s[tag=aj.lapras.animation.surfacewater_idle.playing] run function animated_java:lapras/animations/surfacewater_idle/zzz/on_tick
particle minecraft:cloud ~ ~.5 ~ .5 .1 .5 0 5 normal @a