# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage ssbrc:entity/pokemon/dugtrio/rig rig_hash set value '2974a4e473513002e6fa883bceada53bcb0c2949dabf3d8782e968a6dda4a802'
scoreboard objectives add aj.ground_idle.frame dummy