# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
execute at @s on passengers if entity @s[tag=aj.global.data] run function animated_java:gastly/on_tick/transform_floating_entities
execute at @s on passengers run rotate @s ~ ~