# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:gastly rig_hash set value '06eee0eb9b8e4fd506718936519ef2879b8843a37297532c78ce2a7c2c0c973d'
scoreboard objectives add aj.ground_idle.frame dummy