# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.geodude.root] run return 0
execute on passengers if entity @s[tag=aj.geodude.data] unless data entity @s {data:{rigHash: 'c036448e326819874301d71fbdd0ca93b4007167cef644804d7395b8b9bed86e'}} on vehicle run function animated_java:geodude/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1