# player adv logic for getting bit 13 at value 0. Generated by generate.py.
# run from advancement bit_13_0

advancement revoke @s only gm4_hooked_entity-1.0:bit_13_0

data modify storage gm4_hooked_entity:temp bit_data set value {bit_score:"gm4_hooked_entity.id_bit.13=0", bit:"13"}
data modify storage gm4_hooked_entity:temp bit_data.UUID set from entity @s UUID
function gm4_hooked_entity-1.0:player/received_bit with storage gm4_hooked_entity:temp bit_data
