# player adv logic for getting bit 6 at value 1. Generated by generate.py.
# run from advancement bit_6_1

advancement revoke @s only gm4_hooked_entity-1.0:bit_6_1

execute if entity @s[gamemode=adventure] run return fail

data modify storage gm4_hooked_entity:temp bit_data set value {bit_score:"gm4_hooked_entity.id_bit.6=1", bit:"6"}
data modify storage gm4_hooked_entity:temp bit_data.UUID set from entity @s UUID
function gm4_hooked_entity-1.0:player/received_bit with storage gm4_hooked_entity:temp bit_data
