# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify entity $(base) start_interpolation set value -1
$data modify entity $(middle) start_interpolation set value -1
$data modify entity $(top) start_interpolation set value -1