# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.sudowoodo.animation.ground_idle.playing
tag @s remove aj.sudowoodo.animation.animation_sudowoodo_blink.playing
tag @s remove aj.sudowoodo.animation.animation_sudowoodo_cry.playing