# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.metapod.node.body_segment3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_body_segment3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.metapod.node.body_segment1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_body_segment1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.metapod.node.eyelid_right1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_eyelid_right1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.metapod.node.eye_right1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_eye_right1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.metapod.node.eyelid_left1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_eyelid_left1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.metapod.node.eye_left1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_eye_left1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.metapod.node.body1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_body1 set from storage animated_java:gu out