# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_closed_mouth_left1) {transformation: [1f,0f,0f,-0.2456f,0f,0.9986f,0.0523f,0.5513f,0f,-0.0523f,0.9986f,-0.3047f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_closed_mouth_right1) {transformation: [1f,0f,0f,0.3169f,0f,0.9986f,0.0523f,0.5513f,0f,-0.0523f,0.9986f,-0.3047f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_closed_mouth1) {transformation: [1f,0f,0f,0.0982f,0f,0.9986f,0.0523f,0.5201f,0f,-0.0523f,0.9986f,-0.3031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth_half_open1) {transformation: [1f,0f,0f,0.0357f,0f,0.9986f,0.0523f,0.4889f,0f,-0.0523f,0.9986f,-0.3014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth_full_open1) {transformation: [1f,0f,0f,0.0357f,0f,0.9986f,0.0523f,0.5672f,0f,-0.0523f,0.9986f,-0.2993f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tougue9) {transformation: [0f,0f,0f,0.0357f,0f,0f,0f,0.4831f,0f,0f,0f,-0.1134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tougue8) {transformation: [0f,0f,0f,0.0357f,0f,0f,0f,0.4831f,0f,0f,0f,-0.1134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tougue7) {transformation: [0f,0f,0f,0.0357f,0f,0f,0f,0.4831f,0f,0f,0f,-0.1134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tougue6) {transformation: [0f,0f,0f,0.0357f,0f,0f,0f,0.4831f,0f,0f,0f,-0.1134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tougue1) {transformation: [0f,0f,0f,0.0357f,0f,0f,0f,0.4831f,0f,0f,0f,-0.1134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth_tongue_full_open1) {transformation: [1f,0f,0f,0.0357f,0f,0.9986f,0.0523f,0.5048f,0f,-0.0523f,0.9986f,-0.296f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blush_right1) {transformation: [1f,0f,0f,0.3732f,0f,0.9986f,0.0523f,0.5734f,0f,-0.0523f,0.9986f,-0.1807f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blush_left1) {transformation: [1f,0f,0f,-0.3018f,0f,0.9986f,0.0523f,0.5734f,0f,-0.0523f,0.9986f,-0.1807f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_eye_rotation1) {transformation: [1f,0f,0f,-0.0737f,0f,1f,0.0087f,0.7073f,0f,-0.0087f,1f,-0.3312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_angry_eye1) {transformation: [1f,0f,0f,0.1138f,0f,1f,0.0087f,0.6614f,0f,-0.0087f,1f,-0.2121f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_pupil1) {transformation: [1f,0f,0f,-0.1675f,0f,1f,0.0087f,0.7384f,0f,-0.0087f,1f,-0.3378f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_pupil_closed3) {transformation: [1f,0f,0f,-0.1518f,0f,1f,0.0087f,0.7073f,0f,-0.0087f,1f,-0.3312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_pupil_closed1) {transformation: [1f,0f,0f,-0.2456f,0f,1f,0.0087f,0.7385f,0f,-0.0087f,1f,-0.3315f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_eye_rotation1) {transformation: [1f,0f,0f,0.145f,0f,1f,0.0087f,0.7073f,0f,-0.0087f,1f,-0.3312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_angry_eye1) {transformation: [1f,0f,0f,-0.0425f,0f,1f,0.0087f,0.6614f,0f,-0.0087f,1f,-0.2121f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_pupil1) {transformation: [1f,0f,0f,0.2388f,0f,1f,0.0087f,0.7384f,0f,-0.0087f,1f,-0.3378f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_pupil_closed3) {transformation: [1f,0f,0f,0.2232f,0f,1f,0.0087f,0.7073f,0f,-0.0087f,1f,-0.3312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_pupil_closed1) {transformation: [1f,0f,0f,0.3169f,0f,1f,0.0087f,0.7385f,0f,-0.0087f,1f,-0.3315f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso1) {transformation: [1f,0f,0f,0.0357f,0f,0.9986f,0.0523f,0.7081f,0f,-0.0523f,0.9986f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"gas":{"px":0.035661071037125326,"py":0.596344226179289,"pz":0.2561993782190114,"ry":360,"rx":87.0000000000002}}}
function animated_java:gastly/animations/ground_idle/zzz/frames/on_tick/transform_floating_entities