# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_closed_mouth_left1) {transformation: [1f,0f,0f,-0.2891f,0f,0.9803f,0.1976f,0.4591f,0f,-0.1976f,0.9803f,-0.2786f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_closed_mouth_right1) {transformation: [1f,0f,0f,0.2734f,0f,0.9803f,0.1976f,0.4591f,0f,-0.1976f,0.9803f,-0.2786f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_closed_mouth1) {transformation: [1f,0f,0f,0.0546f,0f,0.9803f,0.1976f,0.4285f,0f,-0.1976f,0.9803f,-0.2724f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth_half_open1) {transformation: [1f,0f,0f,-0.0079f,0f,0.9803f,0.1976f,0.3979f,0f,-0.1976f,0.9803f,-0.2662f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth_full_open1) {transformation: [1f,0f,0f,-0.0079f,0f,0.9803f,0.1976f,0.4757f,0f,-0.1976f,0.9803f,-0.2755f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tougue9) {transformation: [0f,0f,0f,-0.0079f,0f,0f,0f,0.4196f,0f,0f,0f,-0.0793f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tougue8) {transformation: [0f,0f,0f,-0.0079f,0f,0f,0f,0.4196f,0f,0f,0f,-0.0793f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tougue7) {transformation: [0f,0f,0f,-0.0079f,0f,0f,0f,0.4196f,0f,0f,0f,-0.0793f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tougue6) {transformation: [0f,0f,0f,-0.0079f,0f,0f,0f,0.4196f,0f,0f,0f,-0.0793f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tougue1) {transformation: [0f,0f,0f,-0.0079f,0f,0f,0f,0.4196f,0f,0f,0f,-0.0793f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth_tongue_full_open1) {transformation: [1f,0f,0f,-0.0079f,0f,0.9803f,0.1976f,0.4144f,0f,-0.1976f,0.9803f,-0.2632f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blush_right1) {transformation: [1f,0f,0f,0.3296f,0f,0.9803f,0.1976f,0.4992f,0f,-0.1976f,0.9803f,-0.1591f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blush_left1) {transformation: [1f,0f,0f,-0.3454f,0f,0.9803f,0.1976f,0.4992f,0f,-0.1976f,0.9803f,-0.1591f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_eye_rotation1) {transformation: [1f,0f,0f,-0.1173f,0f,0.988f,0.1546f,0.6096f,0f,-0.1546f,0.988f,-0.3276f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_angry_eye1) {transformation: [1f,0f,0f,0.0702f,0f,0.988f,0.1546f,0.5816f,0f,-0.1546f,0.988f,-0.203f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_pupil1) {transformation: [1f,0f,0f,-0.211f,0f,0.988f,0.1546f,0.6395f,0f,-0.1546f,0.988f,-0.3386f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_pupil_closed3) {transformation: [1f,0f,0f,-0.1954f,0f,0.988f,0.1546f,0.6096f,0f,-0.1546f,0.988f,-0.3276f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_pupil_closed1) {transformation: [1f,0f,0f,-0.2891f,0f,0.988f,0.1546f,0.6404f,0f,-0.1546f,0.988f,-0.3324f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_eye_rotation1) {transformation: [1f,0f,0f,0.1015f,0f,0.988f,0.1546f,0.6096f,0f,-0.1546f,0.988f,-0.3276f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_angry_eye1) {transformation: [1f,0f,0f,-0.086f,0f,0.988f,0.1546f,0.5816f,0f,-0.1546f,0.988f,-0.203f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_pupil1) {transformation: [1f,0f,0f,0.1952f,0f,0.988f,0.1546f,0.6395f,0f,-0.1546f,0.988f,-0.3386f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_pupil_closed3) {transformation: [1f,0f,0f,0.1796f,0f,0.988f,0.1546f,0.6096f,0f,-0.1546f,0.988f,-0.3276f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_pupil_closed1) {transformation: [1f,0f,0f,0.2734f,0f,0.988f,0.1546f,0.6404f,0f,-0.1546f,0.988f,-0.3324f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso1) {transformation: [1f,0f,0f,-0.0079f,0f,0.9803f,0.1976f,0.6587f,0f,-0.1976f,0.9803f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"gas":{"px":-0.007889360870070104,"py":0.5855973780459557,"pz":0.2697683472095152,"ry":0,"rx":78.60518179650177}}}
function animated_java:gastly/animations/ground_idle/zzz/frames/on_tick/transform_floating_entities