# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_closed_mouth_left1) {transformation: [1f,-0.0064f,-0.0003f,-0.2506f,0.0064f,0.999f,0.0433f,0.5552f,0f,-0.0433f,0.9991f,-0.3061f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_closed_mouth_right1) {transformation: [1f,-0.0064f,-0.0003f,0.3119f,0.0064f,0.999f,0.0433f,0.5588f,0f,-0.0433f,0.9991f,-0.3061f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_closed_mouth1) {transformation: [1f,-0.0064f,-0.0003f,0.0933f,0.0064f,0.999f,0.0433f,0.5262f,0f,-0.0433f,0.9991f,-0.3048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth_half_open1) {transformation: [1f,-0.0064f,-0.0003f,0.031f,0.0064f,0.999f,0.0433f,0.4946f,0f,-0.0433f,0.9991f,-0.3034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth_full_open1) {transformation: [1f,-0.0064f,-0.0003f,0.0305f,0.0064f,0.999f,0.0433f,0.5729f,0f,-0.0433f,0.9991f,-0.3005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tougue9) {transformation: [0f,0f,0f,0.0311f,0f,0f,0f,0.4871f,0f,0f,0f,-0.1154f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tougue8) {transformation: [0f,0f,0f,0.0311f,0f,0f,0f,0.4871f,0f,0f,0f,-0.1154f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tougue7) {transformation: [0f,0f,0f,0.0311f,0f,0f,0f,0.4871f,0f,0f,0f,-0.1154f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tougue6) {transformation: [0f,0f,0f,0.0311f,0f,0f,0f,0.4871f,0f,0f,0f,-0.1154f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tougue1) {transformation: [0f,0f,0f,0.0311f,0f,0f,0f,0.4871f,0f,0f,0f,-0.1154f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth_tongue_full_open1) {transformation: [1f,-0.0064f,-0.0003f,0.0309f,0.0064f,0.999f,0.0433f,0.5105f,0f,-0.0433f,0.9991f,-0.2978f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blush_right1) {transformation: [1f,-0.0064f,-0.0003f,0.368f,0.0064f,0.999f,0.0433f,0.5802f,0f,-0.0433f,0.9991f,-0.1819f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blush_left1) {transformation: [1f,-0.0064f,-0.0003f,-0.307f,0.0064f,0.999f,0.0433f,0.5759f,0f,-0.0433f,0.9991f,-0.1819f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_eye_rotation1) {transformation: [1f,-0.0064f,0f,-0.0797f,0.0064f,1f,-0.0003f,0.7125f,0f,0.0003f,1f,-0.3312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_angry_eye1) {transformation: [1f,-0.0064f,0f,0.1081f,0.0064f,1f,-0.0003f,0.6668f,0f,0.0003f,1f,-0.2125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_pupil1) {transformation: [1f,-0.0064f,0f,-0.1737f,0.0064f,1f,-0.0003f,0.7432f,0f,0.0003f,1f,-0.3375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_pupil_closed3) {transformation: [1f,-0.0064f,0f,-0.1579f,0.0064f,1f,-0.0003f,0.712f,0f,0.0003f,1f,-0.3312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_pupil_closed1) {transformation: [1f,-0.0064f,0f,-0.2518f,0.0064f,1f,-0.0003f,0.7426f,0f,0.0003f,1f,-0.3312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_eye_rotation1) {transformation: [1f,-0.0064f,0f,0.139f,0.0064f,1f,-0.0003f,0.7139f,0f,0.0003f,1f,-0.3312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_angry_eye1) {transformation: [1f,-0.0064f,0f,-0.0482f,0.0064f,1f,-0.0003f,0.6658f,0f,0.0003f,1f,-0.2125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_pupil1) {transformation: [1f,-0.0064f,0f,0.2325f,0.0064f,1f,-0.0003f,0.7458f,0f,0.0003f,1f,-0.3375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_pupil_closed3) {transformation: [1f,-0.0064f,0f,0.2171f,0.0064f,1f,-0.0003f,0.7144f,0f,0.0003f,1f,-0.3312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_pupil_closed1) {transformation: [1f,-0.0064f,0f,0.3107f,0.0064f,1f,-0.0003f,0.7463f,0f,0.0003f,1f,-0.3312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso1) {transformation: [1f,-0.0064f,-0.0003f,0.0296f,0.0064f,0.999f,0.0433f,0.7111f,0f,-0.0433f,0.9991f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"gas":{"px":0.03037902937203527,"py":0.5970054820217161,"pz":0.25518008968970196,"ry":351.53898472769805,"rx":87.48994544122598}}}
function animated_java:gastly/animations/ground_idle/zzz/frames/on_tick/transform_floating_entities