# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_closed_mouth_left1) {transformation: [1f,0f,0f,-0.2363f,0f,0.9858f,0.1682f,0.4831f,0f,-0.1682f,0.9858f,-0.2844f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_closed_mouth_right1) {transformation: [1f,0f,0f,0.3262f,0f,0.9858f,0.1682f,0.4831f,0f,-0.1682f,0.9858f,-0.2844f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_closed_mouth1) {transformation: [1f,0f,0f,0.1074f,0f,0.9858f,0.1682f,0.4523f,0f,-0.1682f,0.9858f,-0.2791f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth_half_open1) {transformation: [1f,0f,0f,0.0449f,0f,0.9858f,0.1682f,0.4215f,0f,-0.1682f,0.9858f,-0.2739f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth_full_open1) {transformation: [1f,0f,0f,0.0449f,0f,0.9858f,0.1682f,0.4995f,0f,-0.1682f,0.9858f,-0.2809f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tougue9) {transformation: [0f,0f,0f,0.0449f,0f,0f,0f,0.4376f,0f,0f,0f,-0.0864f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tougue8) {transformation: [0f,0f,0f,0.0449f,0f,0f,0f,0.4376f,0f,0f,0f,-0.0864f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tougue7) {transformation: [0f,0f,0f,0.0449f,0f,0f,0f,0.4376f,0f,0f,0f,-0.0864f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tougue6) {transformation: [0f,0f,0f,0.0449f,0f,0f,0f,0.4376f,0f,0f,0f,-0.0864f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tougue1) {transformation: [0f,0f,0f,0.0449f,0f,0f,0f,0.4376f,0f,0f,0f,-0.0864f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth_tongue_full_open1) {transformation: [1f,0f,0f,0.0449f,0f,0.9858f,0.1682f,0.4379f,0f,-0.1682f,0.9858f,-0.2703f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blush_right1) {transformation: [1f,0f,0f,0.3824f,0f,0.9858f,0.1682f,0.5195f,0f,-0.1682f,0.9858f,-0.1638f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blush_left1) {transformation: [1f,0f,0f,-0.2926f,0f,0.9858f,0.1682f,0.5195f,0f,-0.1682f,0.9858f,-0.1638f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_eye_rotation1) {transformation: [1f,0f,0f,-0.0644f,0f,0.9921f,0.1251f,0.6349f,0f,-0.1251f,0.9921f,-0.3289f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_angry_eye1) {transformation: [1f,0f,0f,0.1231f,0f,0.9921f,0.1251f,0.6032f,0f,-0.1251f,0.9921f,-0.2052f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_pupil1) {transformation: [1f,0f,0f,-0.1582f,0f,0.9921f,0.1251f,0.6651f,0f,-0.1251f,0.9921f,-0.339f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_pupil_closed3) {transformation: [1f,0f,0f,-0.1426f,0f,0.9921f,0.1251f,0.6349f,0f,-0.1251f,0.9921f,-0.3289f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_pupil_closed1) {transformation: [1f,0f,0f,-0.2363f,0f,0.9921f,0.1251f,0.6659f,0f,-0.1251f,0.9921f,-0.3328f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_eye_rotation1) {transformation: [1f,0f,0f,0.1543f,0f,0.9921f,0.1251f,0.6349f,0f,-0.1251f,0.9921f,-0.3289f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_angry_eye1) {transformation: [1f,0f,0f,-0.0332f,0f,0.9921f,0.1251f,0.6032f,0f,-0.1251f,0.9921f,-0.2052f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_pupil1) {transformation: [1f,0f,0f,0.2481f,0f,0.9921f,0.1251f,0.6651f,0f,-0.1251f,0.9921f,-0.339f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_pupil_closed3) {transformation: [1f,0f,0f,0.2324f,0f,0.9921f,0.1251f,0.6349f,0f,-0.1251f,0.9921f,-0.3289f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_pupil_closed1) {transformation: [1f,0f,0f,0.3262f,0f,0.9921f,0.1251f,0.6659f,0f,-0.1251f,0.9921f,-0.3328f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso1) {transformation: [1f,0f,0f,0.0449f,0f,0.9858f,0.1682f,0.6743f,0f,-0.1682f,0.9858f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"gas":{"px":0.04493557097600637,"py":0.593115411518925,"pz":0.26746426304263754,"ry":360,"rx":80.316085755488}}}
function animated_java:gastly/animations/ground_idle/zzz/frames/on_tick/transform_floating_entities