# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.dugtrio.root] run return 0
execute if entity @s[tag=aj.dugtrio.animation.ground_idle.playing] run function animated_java:dugtrio/animations/ground_idle/zzz/on_tick