# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:geodude rig_hash set value '7a25ce852919b2f2fb462549704c207c0fd8e426e56ad5351551dd454296b1a0'
scoreboard objectives add aj.ground_idle.frame dummy