# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$kill $(body_segment3)
$kill $(body_segment1)
$kill $(eyelid_right1)
$kill $(eye_right1)
$kill $(eyelid_left1)
$kill $(eye_left1)
$kill $(body1)