# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.lapras.root] run return 0
execute on passengers if entity @s[tag=aj.lapras.data] unless data entity @s {data:{rigHash: 'ef07f6d7efc75863790d47b401c106c81257c930fd8066d4303f4b351e8b8157'}} on vehicle run function animated_java:lapras/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1