# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(nose1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(pupil_left1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(eyelid_left1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(eye_left1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(pupil_right1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(eyelid_right1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(eye_right1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(body3) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(body1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(ground1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i