# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.closed_mouth_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_closed_mouth_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.closed_mouth_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_closed_mouth_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.closed_mouth1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_closed_mouth1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.mouth_half_open1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_mouth_half_open1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.mouth_full_open1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_mouth_full_open1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.tougue9] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tougue9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.tougue8] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tougue8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.tougue7] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tougue7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.tougue6] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tougue6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.tougue1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tougue1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.mouth_tongue_full_open1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_mouth_tongue_full_open1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.blush_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_blush_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.blush_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_blush_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.left_eye_rotation1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_eye_rotation1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.left_angry_eye1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_angry_eye1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.left_pupil1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_pupil1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.left_pupil_closed3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_pupil_closed3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.left_pupil_closed1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_pupil_closed1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.right_eye_rotation1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_eye_rotation1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.right_angry_eye1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_angry_eye1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.right_pupil1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_pupil1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.right_pupil_closed3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_pupil_closed3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.right_pupil_closed1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_pupil_closed1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gastly.bone.torso1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_torso1 set from storage aj:uuid main.out