# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.lapras.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'lapras', 'function_path': 'animated_java:lapras/animations/animation_lapras_surfacewater_idle/next_frame'}
execute if score @s aj.animation_lapras_surfacewater_idle.frame matches 157.. run scoreboard players set @s aj.animation_lapras_surfacewater_idle.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.animation_lapras_surfacewater_idle.frame
execute at @s run function animated_java:lapras/animations/animation_lapras_surfacewater_idle/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.animation_lapras_surfacewater_idle.frame 1