# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.metapod.root] run return 0
execute on passengers if entity @s[tag=aj.metapod.data] unless data entity @s {data:{rigHash: '18ec036c64ec7e78331be4561f5b0557cdc91a5aeb68628c95faa434fd8fc1c8'}} on vehicle run function animated_java:metapod/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1