# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:magnemite/animations/pause_all
tag @s add aj.magnemite.animation.air_idle.playing
scoreboard players set @s aj.air_idle.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:magnemite/animations/air_idle/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only