# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(body_segment3) ~ ~ ~ ~ ~
$execute as $(body_segment3) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(body_segment1) ~ ~ ~ ~ ~
$execute as $(body_segment1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eyelid_right1) ~ ~ ~ ~ ~
$execute as $(eyelid_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eye_right1) ~ ~ ~ ~ ~
$execute as $(eye_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eyelid_left1) ~ ~ ~ ~ ~
$execute as $(eyelid_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eye_left1) ~ ~ ~ ~ ~
$execute as $(eye_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(body1) ~ ~ ~ ~ ~
$execute as $(body1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1