# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(body_segment3) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.0938f,0f,0f,-1f,-0.5f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(body_segment1) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.125f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(eyelid_right1) { transformation: [-1f,0f,0f,-0.1825f,0f,0.9848f,-0.1736f,0.5652f,0f,-0.1736f,-0.9848f,0.2966f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(eye_right1) { transformation: [-1f,0f,0f,-0.2194f,0f,0.9848f,-0.1736f,0.5625f,0f,-0.1736f,-0.9848f,0.2813f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(eyelid_left1) { transformation: [-1f,0f,0f,0.1825f,0f,0.9848f,-0.1736f,0.5652f,0f,-0.1736f,-0.9848f,0.2966f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(eye_left1) { transformation: [-1f,0f,0f,0.2194f,0f,0.9848f,-0.1736f,0.5625f,0f,-0.1736f,-0.9848f,0.2813f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(body1) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3528f,0f,0f,-1f,-0.101f,0f,0f,0f,1f], start_interpolation: -1 }