# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '8a028ef5cb88ec9872078f49197d3b83babece4dfc5dd2d24d864c9274da20c6'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack