# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(body_segment3) run function ssbrc:entity/pokemon/metapod/rig/variants/shiny/zzz/apply_to_node_body_segment3
$execute as $(body_segment1) run function ssbrc:entity/pokemon/metapod/rig/variants/shiny/zzz/apply_to_node_body_segment1
$execute as $(eyelid_right1) run function ssbrc:entity/pokemon/metapod/rig/variants/shiny/zzz/apply_to_node_eyelid_right1
$execute as $(eye_right1) run function ssbrc:entity/pokemon/metapod/rig/variants/shiny/zzz/apply_to_node_eye_right1
$execute as $(eyelid_left1) run function ssbrc:entity/pokemon/metapod/rig/variants/shiny/zzz/apply_to_node_eyelid_left1
$execute as $(eye_left1) run function ssbrc:entity/pokemon/metapod/rig/variants/shiny/zzz/apply_to_node_eye_left1
$execute as $(body1) run function ssbrc:entity/pokemon/metapod/rig/variants/shiny/zzz/apply_to_node_body1