# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(mouth) ~ ~ ~ ~ ~
$execute as $(mouth) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_wing) ~ ~ ~ ~ ~
$execute as $(right_wing) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left_wing) ~ ~ ~ ~ ~
$execute as $(left_wing) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(beat) ~ ~ ~ ~ ~
$execute as $(beat) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1