# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function ssbrc:game/entity/npc/pokemon/gastly/rig/zzz/reset_floating_entities
function ssbrc:game/entity/npc/pokemon/gastly/rig/zzz/apply_default_pose_to_nodes with storage animated_java:temp entry.data.uuids_by_name
