# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage ssbrc:entity/pokemon/sudowoodo/rig rig_hash set value '3088e08034358009a14f2babce5acbaa782770c50fb7be5bed934a6290c463b8'
scoreboard objectives add aj.ground_idle.frame dummy
scoreboard objectives add aj.animation_sudowoodo_blink.frame dummy
scoreboard objectives add aj.animation_sudowoodo_cry.frame dummy