# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(nose1) ~ ~ ~ ~ ~
$execute as $(nose1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(pupil_left1) ~ ~ ~ ~ ~
$execute as $(pupil_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eyelid_left1) ~ ~ ~ ~ ~
$execute as $(eyelid_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eye_left1) ~ ~ ~ ~ ~
$execute as $(eye_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(pupil_right1) ~ ~ ~ ~ ~
$execute as $(pupil_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eyelid_right1) ~ ~ ~ ~ ~
$execute as $(eyelid_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eye_right1) ~ ~ ~ ~ ~
$execute as $(eye_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(body3) ~ ~ ~ ~ ~
$execute as $(body3) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(body1) ~ ~ ~ ~ ~
$execute as $(body1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(ground1) ~ ~ ~ ~ ~
$execute as $(ground1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1