# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(nose1) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.4531f,0f,0f,-1f,0.2188f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(pupil_left1) { transformation: [-1f,0f,0f,0.0937f,0f,1f,0f,0.625f,0f,0f,-1f,0.2206f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(eyelid_left1) { transformation: [-1f,0f,0f,0.0937f,0f,1f,0f,0.5938f,0f,0f,-1f,0.1831f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(eye_left1) { transformation: [-1f,0f,0f,0.0937f,0f,1f,0f,0.5938f,0f,0f,-1f,0.22f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(pupil_right1) { transformation: [-1f,0f,0f,-0.0938f,0f,1f,0f,0.625f,0f,0f,-1f,0.2206f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(eyelid_right1) { transformation: [-1f,0f,0f,-0.0938f,0f,1f,0f,0.5938f,0f,0f,-1f,0.1831f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(eye_right1) { transformation: [-1f,0f,0f,-0.0938f,0f,1f,0f,0.5938f,0f,0f,-1f,0.22f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(body3) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(body1) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.1875f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(ground1) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }