# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gyarados/animations/surfacewater_swim/zzz/apply_frame {frame: 160}
scoreboard players add @s aj.surfacewater_swim.frame 1