# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.beat.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'beat', 'function_path': 'animated_java:beat/variants/gold_default_/apply'}
execute on passengers if entity @s[tag=aj.beat.bone.left_foot] run function animated_java:beat/variants/gold_default_/zzz/0
execute on passengers if entity @s[tag=aj.beat.bone.right_foot] run function animated_java:beat/variants/gold_default_/zzz/1
execute on passengers if entity @s[tag=aj.beat.bone.mouth] run function animated_java:beat/variants/gold_default_/zzz/2
execute on passengers if entity @s[tag=aj.beat.bone.right_wing] run function animated_java:beat/variants/gold_default_/zzz/3
execute on passengers if entity @s[tag=aj.beat.bone.left_wing] run function animated_java:beat/variants/gold_default_/zzz/4
execute on passengers if entity @s[tag=aj.beat.bone.beat] run function animated_java:beat/variants/gold_default_/zzz/5