# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.neck_spine5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_neck_spine5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.neck_spine2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_neck_spine2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.scale_neck_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_scale_neck_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.scale_neck_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_scale_neck_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.blush_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_blush_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.blush_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_blush_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.left_head_scales] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_head_scales set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.left_head_scales2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_head_scales2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.left_head_scales1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_head_scales1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.right_head_scales] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_head_scales set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.right_head_scales2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_head_scales2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.right_head_scales1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_head_scales1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.head_left_fin1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head_left_fin1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.head_right_fin1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head_right_fin1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.right_whisker16] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_whisker16 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.right_whisker15] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_whisker15 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.right_whisker14] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_whisker14 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.right_whisker13] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_whisker13 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.right_whisker12] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_whisker12 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.right_whisker11] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_whisker11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.right_whisker10] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_whisker10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.right_whisker1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_whisker1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.left_whisker16] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_whisker16 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.left_whisker15] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_whisker15 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.left_whisker14] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_whisker14 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.left_whisker13] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_whisker13 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.left_whisker12] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_whisker12 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.left_whisker11] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_whisker11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.left_whisker10] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_whisker10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.left_whisker1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_whisker1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.upper_left_tooth1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_upper_left_tooth1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.upper_right_tooth1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_upper_right_tooth1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.top_lip1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_top_lip1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.muzzle1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_muzzle1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.jaw_right_tooth1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_jaw_right_tooth1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.jaw_left_tooth1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_jaw_left_tooth1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.tongue1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tongue1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.jaw_lips1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_jaw_lips1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.jaw3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_jaw3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.jaw1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_jaw1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.tear_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tear_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.right_pupil1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_pupil1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.right_sad_pupil1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_sad_pupil1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.right_happy_pupil1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_happy_pupil1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.eyelid_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eyelid_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.eyelid_expressions_right5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eyelid_expressions_right5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.eyelid_expressions_right7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eyelid_expressions_right7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.eyelid_expressions_right6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eyelid_expressions_right6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.right_eye1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_eye1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.tear_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tear_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.left_sad_pupil1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_sad_pupil1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.left_pupil1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_pupil1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.eyelid_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eyelid_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.left_happy_pupil1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_happy_pupil1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.eyelid_expressions_left5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eyelid_expressions_left5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.eyelid_expressions_left7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eyelid_expressions_left7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.eyelid_expressions_left6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eyelid_expressions_left6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.left_eye1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_eye1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.crest_middle5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_crest_middle5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.crest_middle4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_crest_middle4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.crest_middle1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_crest_middle1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.crest_left5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_crest_left5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.crest_left4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_crest_left4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.crest_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_crest_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.crest_center1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_crest_center1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.crest_right5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_crest_right5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.crest_right4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_crest_right4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.crest_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_crest_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.head1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.neck10] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_neck10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.neck9] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_neck9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.neck8] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_neck8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.neck7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_neck7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.neck6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_neck6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.neck_spine6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_neck_spine6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.neck_spine7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_neck_spine7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.tail6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.tail5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.tail4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.segment18] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_segment18 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.segment17] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_segment17 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.segment16] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_segment16 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.segment15] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_segment15 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.segment14] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_segment14 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.segment13] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_segment13 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.segment12] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_segment12 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.segment11] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_segment11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gyarados.node.segment10] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_segment10 set from storage aj:uuid main.out