# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.nose4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_nose4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.pupil_left4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_pupil_left4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.eyelid_left4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eyelid_left4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.eye_left4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eye_left4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.pupil_right4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_pupil_right4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.eyelid_right4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eyelid_right4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.eye_right4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eye_right4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.body1_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body1_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.body5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.ground4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_ground4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.nose5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_nose5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.pupil_left5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_pupil_left5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.eyelid_left5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eyelid_left5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.eye_left5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eye_left5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.pupil_right5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_pupil_right5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.eyelid_right5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eyelid_right5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.eye_right5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eye_right5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.body6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.ground5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_ground5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.nose6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_nose6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.pupil_left6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_pupil_left6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.eyelid_left6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eyelid_left6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.eye_left6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eye_left6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.pupil_right6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_pupil_right6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.eyelid_right6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eyelid_right6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.eye_right6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eye_right6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.body3_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body3_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.body7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dugtrio.node.ground6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_ground6 set from storage aj:uuid main.out