# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage ssbrc:entity/pokemon/tyrogue/rig rig_hash set value '21967db0a7ac4653e29c1a72e00063b38749a95c407f00ed2e7dfce6cbc858ec'
scoreboard objectives add aj.animation_tyrogue_ground_idle.frame dummy
scoreboard objectives add aj.animation_tyrogue_ground_walk.frame dummy
scoreboard objectives add aj.animation_tyrogue_battle_idle.frame dummy
scoreboard objectives add aj.animation_tyrogue_faint.frame dummy
scoreboard objectives add aj.animation_tyrogue_sleep.frame dummy
scoreboard objectives add aj.animation_tyrogue_cry.frame dummy
scoreboard objectives add aj.animation_tyrogue_blink.frame dummy
scoreboard objectives add aj.animation_tyrogue_shoulder_right.frame dummy
scoreboard objectives add aj.animation_tyrogue_shoulder_left.frame dummy
scoreboard objectives add aj.animation_tyrogue_physical.frame dummy