# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 run function ssbrc:fighter/mega_man/beat_call/rig/animations/attack/zzz/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
execute if score @s aj.attack.frame matches -1 run function ssbrc:fighter/mega_man/beat_call/rig/animations/attack/zzz/function_keyframe_loop_patch
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.attack.frame
function ssbrc:fighter/mega_man/beat_call/rig/animations/attack/zzz/apply_frame with storage animated_java:temp args
execute if score @s aj.attack.frame matches 19.. run return run scoreboard players set @s aj.attack.frame -1
scoreboard players add @s aj.attack.frame 1