# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove ssbrc.entity.pokemon.snorlax.rig.animation.ground_idle.playing
tag @s remove ssbrc.entity.pokemon.snorlax.rig.animation.sleep.playing
tag @s remove ssbrc.entity.pokemon.snorlax.rig.animation.sleep2.playing