# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'f02be714a23d317b57d1326fea709aab15c44303c60451d823b75b5df23ca761'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack