# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args merge from entity @s data.locators.root
function animated_java:lapras/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from entity @s data.locators.target
function animated_java:lapras/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from entity @s data.locators.body
function animated_java:lapras/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from entity @s data.locators.head
function animated_java:lapras/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from entity @s data.locators.mouth
function animated_java:lapras/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from entity @s data.locators.special
function animated_java:lapras/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from entity @s data.locators.face
function animated_java:lapras/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from entity @s data.locators.eye1
function animated_java:lapras/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from entity @s data.locators.eye2
function animated_java:lapras/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from entity @s data.locators.horn
function animated_java:lapras/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from entity @s data.locators.physical
function animated_java:lapras/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from entity @s data.locators.jaw_upper
function animated_java:lapras/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from entity @s data.locators.jaw_lower
function animated_java:lapras/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from entity @s data.locators.tail_tip
function animated_java:lapras/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from entity @s data.locators.locator5
function animated_java:lapras/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from entity @s data.locators.locator6
function animated_java:lapras/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args