# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.abra.root] run return 0
execute on passengers if entity @s[tag=aj.abra.data] unless data entity @s {data:{rigHash: '487dda8f1db42240e258bbbf6534c58707fe1d7a33ea2ca7d8932f56778268aa'}} on vehicle run function animated_java:abra/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1