# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "ssbrc:entity/pokemon/lapras/rig"
data modify storage animated_java:temp entry.data.rig_hash set value "32d14e5ebdb8063b34247ad277286d09d068cf847f96f248adeb4365b93a84a2"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.shell2] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/shell2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.shell2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.shell] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/shell
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.shell set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.pupil_right2] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/pupil_right2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.pupil_right2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.pupil_right] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/pupil_right
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.pupil_right set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.eyelid_right] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/eyelid_right
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eyelid_right set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.eye_right] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/eye_right
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye_right set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.pupil_left2] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/pupil_left2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.pupil_left2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.pupil_left] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/pupil_left
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.pupil_left set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.eyelid_left] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/eyelid_left
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eyelid_left set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.eye_left] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/eye_left
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye_left set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.muzzle2] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/muzzle2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.muzzle2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.muzzle] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/muzzle
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.muzzle set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.tongue] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/tongue
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.tongue set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.jaw] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/jaw
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.jaw set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.ear_left] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/ear_left
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ear_left set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.ear_right] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/ear_right
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ear_right set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.head_angle] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/head_angle
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head_angle set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.neck3] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/neck3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.neck3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.neck2] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/neck2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.neck2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.chest2] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/chest2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.chest2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.chest] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/chest
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.chest set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.tail2] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/tail2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.tail2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.tail] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/tail
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.tail set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.torso] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/torso
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.torso set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.leg_front_left4] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/leg_front_left4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg_front_left4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.leg_front_left3] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/leg_front_left3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg_front_left3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.leg_front_left2] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/leg_front_left2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg_front_left2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.leg_front_left] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/leg_front_left
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg_front_left set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.leg_back_left4] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/leg_back_left4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg_back_left4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.leg_back_left3] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/leg_back_left3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg_back_left3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.leg_back_left2] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/leg_back_left2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg_back_left2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.leg_back_left] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/leg_back_left
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg_back_left set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.leg_front_right4] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/leg_front_right4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg_front_right4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.leg_front_right3] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/leg_front_right3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg_front_right3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.leg_front_right2] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/leg_front_right2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg_front_right2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.leg_front_right] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/leg_front_right
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg_front_right set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.leg_back_right4] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/leg_back_right4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg_back_right4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.leg_back_right3] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/leg_back_right3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg_back_right3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.leg_back_right2] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/leg_back_right2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg_back_right2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.node.leg_back_right] run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/as_node/leg_back_right
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg_back_right set from storage animated_java:gu out
function ssbrc:entity/pokemon/lapras/rig/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/variant_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
function ssbrc:entity/pokemon/lapras/rig/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
execute at @s run function ssbrc:entity/pokemon/lapras/rig/zzz/summon/on_summon/rig
tag @s remove aj.new
execute on passengers run tag @s remove aj.new
execute on passengers run ride @s dismount