# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage ssbrc:entity/pokemon/slowpoke/rig rig_hash set value 'ad3bd4ec5baed1922cbaaa59adf0db8da867184044b7aef3afd9d22c30010cd9'
scoreboard objectives add aj.floor_idle.frame dummy
scoreboard objectives add aj.sleep.frame dummy