# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.diglett.root] run return 0
execute on passengers if entity @s[tag=aj.diglett.data] unless data entity @s {data:{rigHash: '14d6996caddeed7076b2ae2e3b7bfd97d87127726dc58441b6ed58bef05318f1'}} on vehicle run function animated_java:diglett/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1