# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function ssbrc:entity/common/tornado/rig/animations/pause_all
tag @s add ssbrc.entity.common.tornado.rig.animation.spin.playing
scoreboard players set @s aj.spin.frame 0
tag @s add aj.transforms_only
execute at @s run function ssbrc:entity/common/tornado/rig/animations/spin/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only