# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(mouth) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(right_wing) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(left_wing) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(beat) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i