# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @s aj.animation_tyrogue_blink.frame 0
tag @s add aj.transforms_only
execute at @s run function ssbrc:entity/pokemon/tyrogue/rig/animations/animation_tyrogue_blink/zzz/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only
tag @s remove ssbrc.entity.pokemon.tyrogue.rig.animation.animation_tyrogue_blink.playing