# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:marker ^0.015625000000000003 ^0.390625 ^-0.031249999999999997 {Tags:['aj.new', 'aj.global.locator', 'aj.jukebox_display.locator', 'aj.jukebox_display.locator.particle']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:jukebox_display/zzz/2
data modify entity @s data.locators.particle.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.jukebox_display.node.item_display] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_item_display set from storage aj:uuid main.out