# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.fgii_graham.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'fgii_graham', 'function_path': 'animated_java:fgii_graham/remove/this'}
function #animated_java:fgii_graham/as_root/on_remove
execute on passengers run kill @s
kill @s