# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.magnemite.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'magnemite', 'function_path': 'animated_java:magnemite/animations/air_idle/play'}
tag @s add aj.magnemite.animation.air_idle.playing
scoreboard players set @s aj.air_idle.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:magnemite/animations/air_idle/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only