# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.eyelid_right1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_eyelid_right1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.eye_right1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_eye_right1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.eyelid_left1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_eyelid_left1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.eye_left1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_eye_left1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.jaw1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_jaw1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.finger_right_thumb3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_finger_right_thumb3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.finger_right_thumb1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_finger_right_thumb1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.finger_right_index3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_finger_right_index3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.finger_right_index1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_finger_right_index1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.finger_right_middle3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_finger_right_middle3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.finger_right_middle1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_finger_right_middle1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.finger_right_ring3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_finger_right_ring3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.finger_right_ring1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_finger_right_ring1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.finger_right_pinky3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_finger_right_pinky3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.finger_right_pinky1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_finger_right_pinky1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.hand_right1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_hand_right1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.arm_right3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_arm_right3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.arm_right1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_arm_right1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.finger_left_thumb3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_finger_left_thumb3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.finger_left_thumb1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_finger_left_thumb1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.finger_left_index3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_finger_left_index3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.finger_left_index1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_finger_left_index1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.finger_left_middle3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_finger_left_middle3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.finger_left_middle1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_finger_left_middle1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.finger_left_ring3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_finger_left_ring3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.finger_left_ring1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_finger_left_ring1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.finger_left_pinky3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_finger_left_pinky3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.finger_left_pinky1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_finger_left_pinky1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.hand_left1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_hand_left1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.arm_left3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_arm_left3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.arm_left1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_arm_left1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.geodude.node.torso1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_torso1 set from storage animated_java:gu out