# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '06eee0eb9b8e4fd506718936519ef2879b8843a37297532c78ce2a7c2c0c973d'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack