# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.gastly.root] run return 0
execute on passengers if entity @s[tag=aj.gastly.data] unless data entity @s {data:{rigHash: '552514054cca70b72ab6aea3df61e0347022391a7447975dbbf3896732bf7926'}} on vehicle run function animated_java:gastly/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1