# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "ssbrc:entity/pokemon/magnemite/rig"
data modify storage animated_java:temp entry.data.rig_hash set value "61fde3bc18a61d9429279b04dd17a34a7eb80a72367231bbae6d8e7387e178d0"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.magnemite.rig.node.pupil1] run function ssbrc:entity/pokemon/magnemite/rig/zzz/summon/as_node/pupil1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.pupil1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.magnemite.rig.node.pupil_closed1] run function ssbrc:entity/pokemon/magnemite/rig/zzz/summon/as_node/pupil_closed1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.pupil_closed1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.magnemite.rig.node.eye1] run function ssbrc:entity/pokemon/magnemite/rig/zzz/summon/as_node/eye1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.magnemite.rig.node.nail_head1] run function ssbrc:entity/pokemon/magnemite/rig/zzz/summon/as_node/nail_head1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.nail_head1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.magnemite.rig.node.nail_left_rotation1] run function ssbrc:entity/pokemon/magnemite/rig/zzz/summon/as_node/nail_left_rotation1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.nail_left_rotation1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.magnemite.rig.node.nail_right_rotation1] run function ssbrc:entity/pokemon/magnemite/rig/zzz/summon/as_node/nail_right_rotation1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.nail_right_rotation1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.magnemite.rig.node.magnet_left1] run function ssbrc:entity/pokemon/magnemite/rig/zzz/summon/as_node/magnet_left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.magnet_left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.magnemite.rig.node.magnet_right1] run function ssbrc:entity/pokemon/magnemite/rig/zzz/summon/as_node/magnet_right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.magnet_right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.magnemite.rig.node.body1] run function ssbrc:entity/pokemon/magnemite/rig/zzz/summon/as_node/body1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body1 set from storage animated_java:gu out
function ssbrc:entity/pokemon/magnemite/rig/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function ssbrc:entity/pokemon/magnemite/rig/zzz/summon/variant_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function ssbrc:entity/pokemon/magnemite/rig/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
execute at @s run function ssbrc:entity/pokemon/magnemite/rig/zzz/summon/on_summon/rig
tag @s remove aj.new
execute on passengers run tag @s remove aj.new
execute on passengers run ride @s dismount