# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.animation.ground_idle.playing] run function ssbrc:entity/pokemon/snorlax/rig/animations/ground_idle/zzz/on_tick
execute if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.animation.sleep.playing] run function ssbrc:entity/pokemon/snorlax/rig/animations/sleep/zzz/on_tick
execute if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.animation.sleep2.playing] run function ssbrc:entity/pokemon/snorlax/rig/animations/sleep2/zzz/on_tick