# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage ssbrc:entity/pokemon/gyarados/rig rig_hash set value 'b62e4ce5ebd3a8969afbd3de99af757b15e38017d0ce78e447f99e49e77c869a'
scoreboard objectives add aj.water_idle.frame dummy
scoreboard objectives add aj.surfacewater_idle.frame dummy
scoreboard objectives add aj.surfacewater_swim.frame dummy