# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function ssbrc:entity/pokemon/metapod/rig/animations/pause_all
tag @s add ssbrc.entity.pokemon.metapod.rig.animation.ground_idle.playing
scoreboard players set @s aj.ground_idle.frame 0
tag @s add aj.transforms_only
execute at @s run function ssbrc:entity/pokemon/metapod/rig/animations/ground_idle/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only