# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.snorlax.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'snorlax', 'function_path': 'animated_java:snorlax/animations/pause_all'}
tag @s remove aj.snorlax.animation.ground_idle.playing
tag @s remove aj.snorlax.animation.sleep.playing
tag @s remove aj.snorlax.animation.sleep2.playing