# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tyrogue/animations/animation_tyrogue_ground_idle/zzz/apply_frame {frame: 80}
scoreboard players add @s aj.animation_tyrogue_ground_idle.frame 1