# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function ssbrc:entity/pokemon/tyrogue/rig/animations/pause_all
scoreboard players set @s aj.animation_tyrogue_shoulder_right.frame 0
tag @s add aj.transforms_only
execute at @s run function ssbrc:entity/pokemon/tyrogue/rig/animations/animation_tyrogue_shoulder_right/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only