# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.diglett.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'diglett', 'function_path': 'animated_java:diglett/variants/default/apply'}
execute on passengers if entity @s[tag=aj.diglett.bone.nose1] run function animated_java:diglett/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.diglett.bone.pupil_left1] run function animated_java:diglett/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.diglett.bone.eyelid_left1] run function animated_java:diglett/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.diglett.bone.eye_left1] run function animated_java:diglett/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.diglett.bone.pupil_right1] run function animated_java:diglett/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.diglett.bone.eyelid_right1] run function animated_java:diglett/variants/default/zzz/5
execute on passengers if entity @s[tag=aj.diglett.bone.eye_right1] run function animated_java:diglett/variants/default/zzz/6
execute on passengers if entity @s[tag=aj.diglett.bone.body3] run function animated_java:diglett/variants/default/zzz/7
execute on passengers if entity @s[tag=aj.diglett.bone.body1] run function animated_java:diglett/variants/default/zzz/8
execute on passengers if entity @s[tag=aj.diglett.bone.ground1] run function animated_java:diglett/variants/default/zzz/9