# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.jukebox_display.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:jukebox_display/as_root/pre_tick
execute on passengers if entity @s[tag=aj.jukebox_display.data] run function animated_java:jukebox_display/root/zzz/1
execute at @s on passengers run rotate @s ~ ~
function #animated_java:jukebox_display/as_root/post_tick