# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.eyelid_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_eyelid_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.eye_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_eye_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.eyelid_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_eyelid_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.eye_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_eye_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.mouth_open1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_mouth_open1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.mouth_closed1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_mouth_closed1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.stem_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_stem_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.stem_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_stem_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.head1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.leaf_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leaf_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.finger_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.leaf_left4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leaf_left4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.finger_left4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_left4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.leaf_left5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leaf_left5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.finger_left5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_left5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.arm_left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.arm_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.leaf_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leaf_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.finger_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.leaf_right4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leaf_right4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.finger_right4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_right4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.leaf_right5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leaf_right5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.finger_right5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_right5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.arm_right3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.arm_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.torso3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_torso3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.torso1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_torso1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.foot_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_foot_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.leg_left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.leg_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.foot_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_foot_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.leg_right3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.sudowoodo.bone.leg_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right1 set from storage aj:uuid main.out