# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function ssbrc:entity/super_mario_bros/boo/rig/animations/pause_all
scoreboard players set @s aj.idle.frame 0
tag @s add aj.transforms_only
execute at @s run function ssbrc:entity/super_mario_bros/boo/rig/animations/idle/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only