# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.sudowoodo.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'sudowoodo', 'function_path': 'animated_java:sudowoodo/animations/animation.sudowoodo.blink/play'}
tag @s add aj.sudowoodo.animation.animation.sudowoodo.blink.playing
scoreboard players set @s aj.animation.sudowoodo.blink.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:sudowoodo/animations/animation.sudowoodo.blink/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only