# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.animation_tyrogue_sleep.frame matches 81.. run scoreboard players set @s aj.animation_tyrogue_sleep.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.animation_tyrogue_sleep.frame
execute at @s run function animated_java:tyrogue/animations/animation_tyrogue_sleep/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.animation_tyrogue_sleep.frame 1