# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(pupil1) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3125f,0f,0f,-1f,0.2563f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(pupil_closed1) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3125f,0f,0f,-1f,0.245f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(eye1) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3125f,0f,0f,-1f,0.2506f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(nail_head1) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.5625f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(nail_left_rotation1) { transformation: [-0.9063f,0f,-0.4226f,0.1719f,0f,1f,0f,0.125f,0.4226f,0f,-0.9063f,0.25f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(nail_right_rotation1) { transformation: [-0.9063f,0f,0.4226f,-0.1719f,0f,1f,0f,0.125f,-0.4226f,0f,-0.9063f,0.25f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(magnet_left1) { transformation: [-1f,0f,0f,0.25f,0f,1f,0f,0.3125f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(magnet_right1) { transformation: [-1f,0f,0f,-0.25f,0f,1f,0f,0.3125f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(body1) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.2813f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }