# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '6c570f7bdb7c082cebfc82e3bc11965638d583b479dff7e586b29f9b3b624dda'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack