# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.pokemon_lapras.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'pokemon_lapras', 'function_path': 'animated_java:pokemon_lapras/animations/animation_lapras_surfacewater_idle/play'}
tag @s add aj.pokemon_lapras.animation.animation_lapras_surfacewater_idle.playing
scoreboard players set @s aj.animation_lapras_surfacewater_idle.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:pokemon_lapras/animations/animation_lapras_surfacewater_idle/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only