# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage ssbrc:entity/pokemon/lapras/rig rig_hash set value '32d14e5ebdb8063b34247ad277286d09d068cf847f96f248adeb4365b93a84a2'
scoreboard objectives add aj.surfacewater_idle.frame dummy