# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.tyrogue.animation.animation_tyrogue_ground_idle.playing] run function animated_java:tyrogue/animations/animation_tyrogue_ground_idle/zzz/on_tick
execute if entity @s[tag=aj.tyrogue.animation.animation_tyrogue_ground_walk.playing] run function animated_java:tyrogue/animations/animation_tyrogue_ground_walk/zzz/on_tick
execute if entity @s[tag=aj.tyrogue.animation.animation_tyrogue_battle_idle.playing] run function animated_java:tyrogue/animations/animation_tyrogue_battle_idle/zzz/on_tick
execute if entity @s[tag=aj.tyrogue.animation.animation_tyrogue_faint.playing] run function animated_java:tyrogue/animations/animation_tyrogue_faint/zzz/on_tick
execute if entity @s[tag=aj.tyrogue.animation.animation_tyrogue_sleep.playing] run function animated_java:tyrogue/animations/animation_tyrogue_sleep/zzz/on_tick
execute if entity @s[tag=aj.tyrogue.animation.animation_tyrogue_cry.playing] run function animated_java:tyrogue/animations/animation_tyrogue_cry/zzz/on_tick
execute if entity @s[tag=aj.tyrogue.animation.animation_tyrogue_blink.playing] run function animated_java:tyrogue/animations/animation_tyrogue_blink/zzz/on_tick
execute if entity @s[tag=aj.tyrogue.animation.animation_tyrogue_shoulder_right.playing] run function animated_java:tyrogue/animations/animation_tyrogue_shoulder_right/zzz/on_tick
execute if entity @s[tag=aj.tyrogue.animation.animation_tyrogue_shoulder_left.playing] run function animated_java:tyrogue/animations/animation_tyrogue_shoulder_left/zzz/on_tick
execute if entity @s[tag=aj.tyrogue.animation.animation_tyrogue_physical.playing] run function animated_java:tyrogue/animations/animation_tyrogue_physical/zzz/on_tick