# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(eyelid_right) ~ ~ ~ ~ ~
$execute as $(eyelid_right) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eye_right) ~ ~ ~ ~ ~
$execute as $(eye_right) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eyelid_left) ~ ~ ~ ~ ~
$execute as $(eyelid_left) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eye_left) ~ ~ ~ ~ ~
$execute as $(eye_left) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(mouth_closed) ~ ~ ~ ~ ~
$execute as $(mouth_closed) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(mouth_open) ~ ~ ~ ~ ~
$execute as $(mouth_open) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(head) ~ ~ ~ ~ ~
$execute as $(head) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(neck) ~ ~ ~ ~ ~
$execute as $(neck) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(finger_left2) ~ ~ ~ ~ ~
$execute as $(finger_left2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(finger_left) ~ ~ ~ ~ ~
$execute as $(finger_left) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(finger_left4) ~ ~ ~ ~ ~
$execute as $(finger_left4) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(finger_left3) ~ ~ ~ ~ ~
$execute as $(finger_left3) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(thumb_left2) ~ ~ ~ ~ ~
$execute as $(thumb_left2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(thumb_left) ~ ~ ~ ~ ~
$execute as $(thumb_left) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(hand_left) ~ ~ ~ ~ ~
$execute as $(hand_left) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(arm_left2) ~ ~ ~ ~ ~
$execute as $(arm_left2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(arm_left) ~ ~ ~ ~ ~
$execute as $(arm_left) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(finger_right2) ~ ~ ~ ~ ~
$execute as $(finger_right2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(finger_right) ~ ~ ~ ~ ~
$execute as $(finger_right) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(finger_right4) ~ ~ ~ ~ ~
$execute as $(finger_right4) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(finger_right3) ~ ~ ~ ~ ~
$execute as $(finger_right3) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(thumb_right2) ~ ~ ~ ~ ~
$execute as $(thumb_right2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(thumb_right) ~ ~ ~ ~ ~
$execute as $(thumb_right) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(hand_right) ~ ~ ~ ~ ~
$execute as $(hand_right) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(arm_right2) ~ ~ ~ ~ ~
$execute as $(arm_right2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(arm_right) ~ ~ ~ ~ ~
$execute as $(arm_right) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(torso) ~ ~ ~ ~ ~
$execute as $(torso) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(foot_right) ~ ~ ~ ~ ~
$execute as $(foot_right) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_right3) ~ ~ ~ ~ ~
$execute as $(leg_right3) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_right2) ~ ~ ~ ~ ~
$execute as $(leg_right2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_right) ~ ~ ~ ~ ~
$execute as $(leg_right) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(foot_left) ~ ~ ~ ~ ~
$execute as $(foot_left) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_left3) ~ ~ ~ ~ ~
$execute as $(leg_left3) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_left2) ~ ~ ~ ~ ~
$execute as $(leg_left2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_left) ~ ~ ~ ~ ~
$execute as $(leg_left) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1