# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.tornado.root] run return 0
execute on passengers if entity @s[tag=aj.tornado.data] unless data entity @s {data:{rigHash: '612a37379982ce361b8cec2408cd49fa61328d8703224c02b036bdb8ff5c23d6'}} on vehicle run function animated_java:tornado/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1