# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.metapod.node.body_segment3] at @s run function animated_java:metapod/variants/shiny/zzz/apply_to_node_body_segment3
execute on passengers if entity @s[tag=aj.metapod.node.body_segment1] at @s run function animated_java:metapod/variants/shiny/zzz/apply_to_node_body_segment1
execute on passengers if entity @s[tag=aj.metapod.node.eyelid_right1] at @s run function animated_java:metapod/variants/shiny/zzz/apply_to_node_eyelid_right1
execute on passengers if entity @s[tag=aj.metapod.node.eye_right1] at @s run function animated_java:metapod/variants/shiny/zzz/apply_to_node_eye_right1
execute on passengers if entity @s[tag=aj.metapod.node.eyelid_left1] at @s run function animated_java:metapod/variants/shiny/zzz/apply_to_node_eyelid_left1
execute on passengers if entity @s[tag=aj.metapod.node.eye_left1] at @s run function animated_java:metapod/variants/shiny/zzz/apply_to_node_eye_left1
execute on passengers if entity @s[tag=aj.metapod.node.body1] at @s run function animated_java:metapod/variants/shiny/zzz/apply_to_node_body1
return 1