# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage ssbrc:entity/pokemon/geodude/rig rig_hash set value '5f6c51472c921fdefb4f9c24c558dc327eb24ec1bd29500d7d0130d1a95b13d8'
scoreboard objectives add aj.ground_idle.frame dummy