# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.tail7] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.tail6] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.tail5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.tail1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.pad_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_pad_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.pad_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_pad_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.jaw1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_jaw1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.eye_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_eye_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.eye_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_eye_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.ear_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.ear_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.head1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.finger_index_right3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_index_right3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.finger_index_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_index_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.finger_middle_right3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_middle_right3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.finger_middle_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_middle_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.finger_pinky_right3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_pinky_right3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.finger_pinky_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_pinky_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.forearm_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_forearm_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.arm_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.finger_index_left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_index_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.finger_index_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_index_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.finger_middle_left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_middle_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.finger_middle_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_middle_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.finger_pinky_left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_pinky_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.finger_pinky_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_finger_pinky_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.forearm_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_forearm_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.arm_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.chest1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chest1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.torso1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_torso1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.toe_outer_right3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_toe_outer_right3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.toe_outer_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_toe_outer_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.toe_inner_right3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_toe_inner_right3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.toe_inner_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_toe_inner_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.toe_back_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_toe_back_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.foot_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_foot_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.knee_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_knee_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.leg_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.toe_outer_left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_toe_outer_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.toe_outer_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_toe_outer_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.toe_inner_left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_toe_inner_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.toe_inner_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_toe_inner_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.toe_back_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_toe_back_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.foot_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_foot_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.knee_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_knee_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.bone.leg_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left1 set from storage aj:uuid main.out