# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove ssbrc.entity.pokemon.gyarados.rig.animation.water_idle.playing
tag @s remove ssbrc.entity.pokemon.gyarados.rig.animation.surfacewater_idle.playing
tag @s remove ssbrc.entity.pokemon.gyarados.rig.animation.surfacewater_swim.playing