# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.slowpoke.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'slowpoke', 'function_path': 'animated_java:slowpoke/variants/shiny/apply'}
execute on passengers if entity @s[tag=aj.slowpoke.bone.tail7] run function animated_java:slowpoke/variants/shiny/zzz/0
execute on passengers if entity @s[tag=aj.slowpoke.bone.tail6] run function animated_java:slowpoke/variants/shiny/zzz/1
execute on passengers if entity @s[tag=aj.slowpoke.bone.tail5] run function animated_java:slowpoke/variants/shiny/zzz/2
execute on passengers if entity @s[tag=aj.slowpoke.bone.tail1] run function animated_java:slowpoke/variants/shiny/zzz/3
execute on passengers if entity @s[tag=aj.slowpoke.bone.ear_left1] run function animated_java:slowpoke/variants/shiny/zzz/4
execute on passengers if entity @s[tag=aj.slowpoke.bone.ear_right1] run function animated_java:slowpoke/variants/shiny/zzz/5
execute on passengers if entity @s[tag=aj.slowpoke.bone.eyelid_left1] run function animated_java:slowpoke/variants/shiny/zzz/6
execute on passengers if entity @s[tag=aj.slowpoke.bone.eye_left1] run function animated_java:slowpoke/variants/shiny/zzz/7
execute on passengers if entity @s[tag=aj.slowpoke.bone.eyelid_right1] run function animated_java:slowpoke/variants/shiny/zzz/8
execute on passengers if entity @s[tag=aj.slowpoke.bone.eye_right1] run function animated_java:slowpoke/variants/shiny/zzz/9
execute on passengers if entity @s[tag=aj.slowpoke.bone.jaw1] run function animated_java:slowpoke/variants/shiny/zzz/10
execute on passengers if entity @s[tag=aj.slowpoke.bone.head1] run function animated_java:slowpoke/variants/shiny/zzz/11
execute on passengers if entity @s[tag=aj.slowpoke.bone.torso1] run function animated_java:slowpoke/variants/shiny/zzz/12
execute on passengers if entity @s[tag=aj.slowpoke.bone.leftfrontleg1] run function animated_java:slowpoke/variants/shiny/zzz/13
execute on passengers if entity @s[tag=aj.slowpoke.bone.leftbackleg1] run function animated_java:slowpoke/variants/shiny/zzz/14
execute on passengers if entity @s[tag=aj.slowpoke.bone.rightfrontleg1] run function animated_java:slowpoke/variants/shiny/zzz/15
execute on passengers if entity @s[tag=aj.slowpoke.bone.rightbackleg1] run function animated_java:slowpoke/variants/shiny/zzz/16