# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "ssbrc:entity/pokemon/dugtrio/rig"
data modify storage animated_java:temp entry.data.rig_hash set value "2974a4e473513002e6fa883bceada53bcb0c2949dabf3d8782e968a6dda4a802"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.nose4] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/nose4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.nose4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.pupil_left4] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/pupil_left4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.pupil_left4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.eyelid_left4] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/eyelid_left4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eyelid_left4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.eye_left4] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/eye_left4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye_left4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.pupil_right4] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/pupil_right4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.pupil_right4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.eyelid_right4] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/eyelid_right4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eyelid_right4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.eye_right4] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/eye_right4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye_right4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.body1_3] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/body1_3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body1_3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.body5] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/body5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body5 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.ground4] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/ground4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ground4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.nose5] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/nose5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.nose5 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.pupil_left5] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/pupil_left5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.pupil_left5 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.eyelid_left5] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/eyelid_left5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eyelid_left5 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.eye_left5] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/eye_left5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye_left5 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.pupil_right5] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/pupil_right5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.pupil_right5 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.eyelid_right5] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/eyelid_right5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eyelid_right5 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.eye_right5] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/eye_right5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye_right5 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.body6] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/body6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body6 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.ground5] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/ground5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ground5 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.nose6] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/nose6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.nose6 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.pupil_left6] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/pupil_left6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.pupil_left6 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.eyelid_left6] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/eyelid_left6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eyelid_left6 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.eye_left6] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/eye_left6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye_left6 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.pupil_right6] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/pupil_right6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.pupil_right6 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.eyelid_right6] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/eyelid_right6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eyelid_right6 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.eye_right6] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/eye_right6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye_right6 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.body3_3] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/body3_3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body3_3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.body7] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/body7
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body7 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.dugtrio.rig.node.ground6] run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/as_node/ground6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ground6 set from storage animated_java:gu out
function ssbrc:entity/pokemon/dugtrio/rig/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/variant_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
execute at @s run function ssbrc:entity/pokemon/dugtrio/rig/zzz/summon/on_summon/rig
tag @s remove aj.new
execute on passengers run tag @s remove aj.new
execute on passengers run ride @s dismount