# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage ssbrc:entity/pokemon/snorlax/rig rig_hash set value '7d05d2717a0616b87464a35fb26a00181146de29a774e7412d83091ee3ab0f4f'
scoreboard objectives add aj.ground_idle.frame dummy
scoreboard objectives add aj.sleep.frame dummy
scoreboard objectives add aj.sleep2.frame dummy