# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(neck_spine5) ~ ~ ~ ~ ~
$execute as $(neck_spine5) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(neck_spine2) ~ ~ ~ ~ ~
$execute as $(neck_spine2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(scale_neck_left1) ~ ~ ~ ~ ~
$execute as $(scale_neck_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(scale_neck_right1) ~ ~ ~ ~ ~
$execute as $(scale_neck_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(blush_right1) ~ ~ ~ ~ ~
$execute as $(blush_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(blush_left1) ~ ~ ~ ~ ~
$execute as $(blush_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left_head_scales) ~ ~ ~ ~ ~
$execute as $(left_head_scales) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left_head_scales2) ~ ~ ~ ~ ~
$execute as $(left_head_scales2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left_head_scales1) ~ ~ ~ ~ ~
$execute as $(left_head_scales1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_head_scales) ~ ~ ~ ~ ~
$execute as $(right_head_scales) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_head_scales2) ~ ~ ~ ~ ~
$execute as $(right_head_scales2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_head_scales1) ~ ~ ~ ~ ~
$execute as $(right_head_scales1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(head_left_fin1) ~ ~ ~ ~ ~
$execute as $(head_left_fin1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(head_right_fin1) ~ ~ ~ ~ ~
$execute as $(head_right_fin1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_whisker16) ~ ~ ~ ~ ~
$execute as $(right_whisker16) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_whisker15) ~ ~ ~ ~ ~
$execute as $(right_whisker15) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_whisker14) ~ ~ ~ ~ ~
$execute as $(right_whisker14) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_whisker13) ~ ~ ~ ~ ~
$execute as $(right_whisker13) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_whisker12) ~ ~ ~ ~ ~
$execute as $(right_whisker12) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_whisker11) ~ ~ ~ ~ ~
$execute as $(right_whisker11) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_whisker10) ~ ~ ~ ~ ~
$execute as $(right_whisker10) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_whisker1) ~ ~ ~ ~ ~
$execute as $(right_whisker1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left_whisker16) ~ ~ ~ ~ ~
$execute as $(left_whisker16) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left_whisker15) ~ ~ ~ ~ ~
$execute as $(left_whisker15) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left_whisker14) ~ ~ ~ ~ ~
$execute as $(left_whisker14) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left_whisker13) ~ ~ ~ ~ ~
$execute as $(left_whisker13) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left_whisker12) ~ ~ ~ ~ ~
$execute as $(left_whisker12) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left_whisker11) ~ ~ ~ ~ ~
$execute as $(left_whisker11) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left_whisker10) ~ ~ ~ ~ ~
$execute as $(left_whisker10) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left_whisker1) ~ ~ ~ ~ ~
$execute as $(left_whisker1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(upper_left_tooth1) ~ ~ ~ ~ ~
$execute as $(upper_left_tooth1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(upper_right_tooth1) ~ ~ ~ ~ ~
$execute as $(upper_right_tooth1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(top_lip1) ~ ~ ~ ~ ~
$execute as $(top_lip1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(muzzle1) ~ ~ ~ ~ ~
$execute as $(muzzle1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(jaw_right_tooth1) ~ ~ ~ ~ ~
$execute as $(jaw_right_tooth1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(jaw_left_tooth1) ~ ~ ~ ~ ~
$execute as $(jaw_left_tooth1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(tongue1) ~ ~ ~ ~ ~
$execute as $(tongue1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(jaw_lips1) ~ ~ ~ ~ ~
$execute as $(jaw_lips1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(jaw3) ~ ~ ~ ~ ~
$execute as $(jaw3) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(jaw1) ~ ~ ~ ~ ~
$execute as $(jaw1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(tear_right1) ~ ~ ~ ~ ~
$execute as $(tear_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_pupil1) ~ ~ ~ ~ ~
$execute as $(right_pupil1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_sad_pupil1) ~ ~ ~ ~ ~
$execute as $(right_sad_pupil1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_happy_pupil1) ~ ~ ~ ~ ~
$execute as $(right_happy_pupil1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eyelid_right1) ~ ~ ~ ~ ~
$execute as $(eyelid_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eyelid_expressions_right5) ~ ~ ~ ~ ~
$execute as $(eyelid_expressions_right5) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eyelid_expressions_right7) ~ ~ ~ ~ ~
$execute as $(eyelid_expressions_right7) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eyelid_expressions_right6) ~ ~ ~ ~ ~
$execute as $(eyelid_expressions_right6) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(right_eye1) ~ ~ ~ ~ ~
$execute as $(right_eye1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(tear_left1) ~ ~ ~ ~ ~
$execute as $(tear_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left_sad_pupil1) ~ ~ ~ ~ ~
$execute as $(left_sad_pupil1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left_pupil1) ~ ~ ~ ~ ~
$execute as $(left_pupil1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eyelid_left1) ~ ~ ~ ~ ~
$execute as $(eyelid_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left_happy_pupil1) ~ ~ ~ ~ ~
$execute as $(left_happy_pupil1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eyelid_expressions_left5) ~ ~ ~ ~ ~
$execute as $(eyelid_expressions_left5) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eyelid_expressions_left7) ~ ~ ~ ~ ~
$execute as $(eyelid_expressions_left7) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eyelid_expressions_left6) ~ ~ ~ ~ ~
$execute as $(eyelid_expressions_left6) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(left_eye1) ~ ~ ~ ~ ~
$execute as $(left_eye1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(crest_middle5) ~ ~ ~ ~ ~
$execute as $(crest_middle5) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(crest_middle4) ~ ~ ~ ~ ~
$execute as $(crest_middle4) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(crest_middle1) ~ ~ ~ ~ ~
$execute as $(crest_middle1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(crest_left5) ~ ~ ~ ~ ~
$execute as $(crest_left5) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(crest_left4) ~ ~ ~ ~ ~
$execute as $(crest_left4) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(crest_left1) ~ ~ ~ ~ ~
$execute as $(crest_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(crest_center1) ~ ~ ~ ~ ~
$execute as $(crest_center1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(crest_right5) ~ ~ ~ ~ ~
$execute as $(crest_right5) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(crest_right4) ~ ~ ~ ~ ~
$execute as $(crest_right4) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(crest_right1) ~ ~ ~ ~ ~
$execute as $(crest_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(head1) ~ ~ ~ ~ ~
$execute as $(head1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(neck10) ~ ~ ~ ~ ~
$execute as $(neck10) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(neck9) ~ ~ ~ ~ ~
$execute as $(neck9) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(neck8) ~ ~ ~ ~ ~
$execute as $(neck8) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(neck7) ~ ~ ~ ~ ~
$execute as $(neck7) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(neck6) ~ ~ ~ ~ ~
$execute as $(neck6) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(neck_spine6) ~ ~ ~ ~ ~
$execute as $(neck_spine6) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(neck_spine7) ~ ~ ~ ~ ~
$execute as $(neck_spine7) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(tail6) ~ ~ ~ ~ ~
$execute as $(tail6) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(tail5) ~ ~ ~ ~ ~
$execute as $(tail5) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(tail4) ~ ~ ~ ~ ~
$execute as $(tail4) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(segment18) ~ ~ ~ ~ ~
$execute as $(segment18) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(segment17) ~ ~ ~ ~ ~
$execute as $(segment17) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(segment16) ~ ~ ~ ~ ~
$execute as $(segment16) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(segment15) ~ ~ ~ ~ ~
$execute as $(segment15) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(segment14) ~ ~ ~ ~ ~
$execute as $(segment14) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(segment13) ~ ~ ~ ~ ~
$execute as $(segment13) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(segment12) ~ ~ ~ ~ ~
$execute as $(segment12) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(segment11) ~ ~ ~ ~ ~
$execute as $(segment11) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(segment10) ~ ~ ~ ~ ~
$execute as $(segment10) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1