# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.lapras.root] run return 0
execute on passengers if entity @s[tag=aj.lapras.data] unless data entity @s {data:{rigHash: 'b6f7fee7786582f4249ba6ca172ac7d26b101a540bf29d71af969d76e242f3a8'}} on vehicle run function animated_java:lapras/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1