# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(tail7) ~ ~ ~ ~ ~
$execute as $(tail7) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(tail6) ~ ~ ~ ~ ~
$execute as $(tail6) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(tail5) ~ ~ ~ ~ ~
$execute as $(tail5) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(tail1) ~ ~ ~ ~ ~
$execute as $(tail1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(ear_left1) ~ ~ ~ ~ ~
$execute as $(ear_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(ear_right1) ~ ~ ~ ~ ~
$execute as $(ear_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eyelid_left1) ~ ~ ~ ~ ~
$execute as $(eyelid_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eye_left1) ~ ~ ~ ~ ~
$execute as $(eye_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eyelid_right1) ~ ~ ~ ~ ~
$execute as $(eyelid_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eye_right1) ~ ~ ~ ~ ~
$execute as $(eye_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(jaw1) ~ ~ ~ ~ ~
$execute as $(jaw1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(head1) ~ ~ ~ ~ ~
$execute as $(head1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(torso1) ~ ~ ~ ~ ~
$execute as $(torso1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leftfrontleg1) ~ ~ ~ ~ ~
$execute as $(leftfrontleg1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leftbackleg1) ~ ~ ~ ~ ~
$execute as $(leftbackleg1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(rightfrontleg1) ~ ~ ~ ~ ~
$execute as $(rightfrontleg1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(rightbackleg1) ~ ~ ~ ~ ~
$execute as $(rightbackleg1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1