# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '183fe7b891e19d830bfc90d177eaf404a0d15ead37416dc0f51cd7ffe42ebfec'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack