# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.metapod.node.body_segment3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body_segment3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.metapod.node.body_segment1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body_segment1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.metapod.node.eyelid_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eyelid_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.metapod.node.eye_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eye_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.metapod.node.eyelid_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eyelid_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.metapod.node.eye_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eye_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.metapod.node.body1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body1 set from storage aj:uuid main.out