# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.metapod.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'metapod', 'function_path': 'animated_java:metapod/variants/default/apply'}
execute on passengers if entity @s[tag=aj.metapod.bone.body_segment3] run function animated_java:metapod/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.metapod.bone.body_segment1] run function animated_java:metapod/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.metapod.bone.eyelid_right1] run function animated_java:metapod/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.metapod.bone.eye_right1] run function animated_java:metapod/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.metapod.bone.eyelid_left1] run function animated_java:metapod/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.metapod.bone.eye_left1] run function animated_java:metapod/variants/default/zzz/5
execute on passengers if entity @s[tag=aj.metapod.bone.body1] run function animated_java:metapod/variants/default/zzz/6