# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage ssbrc:entity/pokemon/diglett/rig rig_hash set value '091aa5aa9d0eda5c22fc98b30107c7083ecb897a7cd452fac37a5b93e1d6334e'
scoreboard objectives add aj.ground_idle.frame dummy