# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.gastly.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'gastly', 'function_path': 'animated_java:gastly/variants/default/apply'}
execute on passengers if entity @s[tag=aj.gastly.bone.closed_mouth_left1] run function animated_java:gastly/variants/default/zzz/apply_to_bone_closed_mouth_left1
execute on passengers if entity @s[tag=aj.gastly.bone.closed_mouth_right1] run function animated_java:gastly/variants/default/zzz/apply_to_bone_closed_mouth_right1
execute on passengers if entity @s[tag=aj.gastly.bone.closed_mouth1] run function animated_java:gastly/variants/default/zzz/apply_to_bone_closed_mouth1
execute on passengers if entity @s[tag=aj.gastly.bone.mouth_half_open1] run function animated_java:gastly/variants/default/zzz/apply_to_bone_mouth_half_open1
execute on passengers if entity @s[tag=aj.gastly.bone.mouth_full_open1] run function animated_java:gastly/variants/default/zzz/apply_to_bone_mouth_full_open1
execute on passengers if entity @s[tag=aj.gastly.bone.tougue9] run function animated_java:gastly/variants/default/zzz/apply_to_bone_tougue9
execute on passengers if entity @s[tag=aj.gastly.bone.tougue8] run function animated_java:gastly/variants/default/zzz/apply_to_bone_tougue8
execute on passengers if entity @s[tag=aj.gastly.bone.tougue7] run function animated_java:gastly/variants/default/zzz/apply_to_bone_tougue7
execute on passengers if entity @s[tag=aj.gastly.bone.tougue6] run function animated_java:gastly/variants/default/zzz/apply_to_bone_tougue6
execute on passengers if entity @s[tag=aj.gastly.bone.tougue1] run function animated_java:gastly/variants/default/zzz/apply_to_bone_tougue1
execute on passengers if entity @s[tag=aj.gastly.bone.mouth_tongue_full_open1] run function animated_java:gastly/variants/default/zzz/apply_to_bone_mouth_tongue_full_open1
execute on passengers if entity @s[tag=aj.gastly.bone.blush_right1] run function animated_java:gastly/variants/default/zzz/apply_to_bone_blush_right1
execute on passengers if entity @s[tag=aj.gastly.bone.blush_left1] run function animated_java:gastly/variants/default/zzz/apply_to_bone_blush_left1
execute on passengers if entity @s[tag=aj.gastly.bone.left_eye_rotation1] run function animated_java:gastly/variants/default/zzz/apply_to_bone_left_eye_rotation1
execute on passengers if entity @s[tag=aj.gastly.bone.left_angry_eye1] run function animated_java:gastly/variants/default/zzz/apply_to_bone_left_angry_eye1
execute on passengers if entity @s[tag=aj.gastly.bone.left_pupil1] run function animated_java:gastly/variants/default/zzz/apply_to_bone_left_pupil1
execute on passengers if entity @s[tag=aj.gastly.bone.left_pupil_closed3] run function animated_java:gastly/variants/default/zzz/apply_to_bone_left_pupil_closed3
execute on passengers if entity @s[tag=aj.gastly.bone.left_pupil_closed1] run function animated_java:gastly/variants/default/zzz/apply_to_bone_left_pupil_closed1
execute on passengers if entity @s[tag=aj.gastly.bone.right_eye_rotation1] run function animated_java:gastly/variants/default/zzz/apply_to_bone_right_eye_rotation1
execute on passengers if entity @s[tag=aj.gastly.bone.right_angry_eye1] run function animated_java:gastly/variants/default/zzz/apply_to_bone_right_angry_eye1
execute on passengers if entity @s[tag=aj.gastly.bone.right_pupil1] run function animated_java:gastly/variants/default/zzz/apply_to_bone_right_pupil1
execute on passengers if entity @s[tag=aj.gastly.bone.right_pupil_closed3] run function animated_java:gastly/variants/default/zzz/apply_to_bone_right_pupil_closed3
execute on passengers if entity @s[tag=aj.gastly.bone.right_pupil_closed1] run function animated_java:gastly/variants/default/zzz/apply_to_bone_right_pupil_closed1
execute on passengers if entity @s[tag=aj.gastly.bone.torso1] run function animated_java:gastly/variants/default/zzz/apply_to_bone_torso1
return 1