# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.magnemite.node.pupil1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_pupil1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.magnemite.node.pupil_closed1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_pupil_closed1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.magnemite.node.eye1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_eye1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.magnemite.node.nail_head1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_nail_head1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.magnemite.node.nail_left_rotation1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_nail_left_rotation1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.magnemite.node.nail_right_rotation1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_nail_right_rotation1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.magnemite.node.magnet_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_magnet_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.magnemite.node.magnet_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_magnet_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.magnemite.node.body1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body1 set from storage aj:uuid main.out