# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:snorlax rig_hash set value 'b989c4dda4ce5ee0252009d4abf26197ac41bf0781fc1ddd9c1db7ed0187f96a'
scoreboard objectives add aj.ground_idle.frame dummy
scoreboard objectives add aj.sleep.frame dummy
scoreboard objectives add aj.sleep2.frame dummy