# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(nose1) run function ssbrc:entity/pokemon/diglett/rig/variants/default/zzz/apply_to_node_nose1
$execute as $(pupil_left1) run function ssbrc:entity/pokemon/diglett/rig/variants/default/zzz/apply_to_node_pupil_left1
$execute as $(eyelid_left1) run function ssbrc:entity/pokemon/diglett/rig/variants/default/zzz/apply_to_node_eyelid_left1
$execute as $(eye_left1) run function ssbrc:entity/pokemon/diglett/rig/variants/default/zzz/apply_to_node_eye_left1
$execute as $(pupil_right1) run function ssbrc:entity/pokemon/diglett/rig/variants/default/zzz/apply_to_node_pupil_right1
$execute as $(eyelid_right1) run function ssbrc:entity/pokemon/diglett/rig/variants/default/zzz/apply_to_node_eyelid_right1
$execute as $(eye_right1) run function ssbrc:entity/pokemon/diglett/rig/variants/default/zzz/apply_to_node_eye_right1
$execute as $(body3) run function ssbrc:entity/pokemon/diglett/rig/variants/default/zzz/apply_to_node_body3
$execute as $(body1) run function ssbrc:entity/pokemon/diglett/rig/variants/default/zzz/apply_to_node_body1
$execute as $(ground1) run function ssbrc:entity/pokemon/diglett/rig/variants/default/zzz/apply_to_node_ground1