# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage ssbrc:entity/super_mario_bros/boo/rig rig_hash set value 'c4bc18c42d1b2fc7db8fc75f2a12d14f6c7d305426ac0749121fbc2fe2f232b5'
scoreboard objectives add aj.idle.frame dummy