# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.diglett.node.nose1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_nose1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.diglett.node.pupil_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_pupil_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.diglett.node.eyelid_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_eyelid_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.diglett.node.eye_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_eye_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.diglett.node.pupil_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_pupil_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.diglett.node.eyelid_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_eyelid_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.diglett.node.eye_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_eye_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.diglett.node.body3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.diglett.node.body1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.diglett.node.ground1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ground1 set from storage aj:uuid main.out