# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tyrogue/animations/shoulder_right/zzz/apply_frame {frame: 20}
scoreboard players add @s aj.shoulder_right.frame 1