# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage ssbrc:entity/metroid/fgii_graham/rig rig_hash set value 'e407d85de62832b64e7f61decc46d06da6d97be79c9bf88da52980b47d851da9'
scoreboard objectives add aj.idle.frame dummy