# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.slowpoke.node.tail7] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_tail7 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.slowpoke.node.tail6] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_tail6 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.slowpoke.node.tail5] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_tail5 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.slowpoke.node.tail1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_tail1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.slowpoke.node.ear_left1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_ear_left1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.slowpoke.node.ear_right1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_ear_right1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.slowpoke.node.eyelid_left1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_eyelid_left1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.slowpoke.node.eye_left1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_eye_left1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.slowpoke.node.eyelid_right1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_eyelid_right1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.slowpoke.node.eye_right1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_eye_right1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.slowpoke.node.jaw1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_jaw1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.slowpoke.node.head1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.slowpoke.node.torso1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_torso1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.slowpoke.node.leftfrontleg1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leftfrontleg1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.slowpoke.node.leftbackleg1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_leftbackleg1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.slowpoke.node.rightfrontleg1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rightfrontleg1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.slowpoke.node.rightbackleg1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rightbackleg1 set from storage animated_java:gu out