# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.floor_idle.frame matches 54.. run scoreboard players set @s aj.floor_idle.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.floor_idle.frame
execute at @s run function animated_java:slowpoke/animations/floor_idle/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.floor_idle.frame 1