# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.slowpoke.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'slowpoke', 'function_path': 'animated_java:slowpoke/animations/floor_idle/stop'}
tag @s remove aj.slowpoke.animation.floor_idle.playing
scoreboard players set @s aj.floor_idle.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:slowpoke/animations/floor_idle/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only