# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "ssbrc:entity/pokemon/metapod/rig"
data modify storage animated_java:temp entry.data.rig_hash set value "3e091eb1d9f5c9c22141033708949b33c0c904354f47cbaaa763452d1977f2e6"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.metapod.rig.node.body_segment3] run function ssbrc:entity/pokemon/metapod/rig/zzz/summon/as_node/body_segment3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body_segment3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.metapod.rig.node.body_segment1] run function ssbrc:entity/pokemon/metapod/rig/zzz/summon/as_node/body_segment1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body_segment1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.metapod.rig.node.eyelid_right1] run function ssbrc:entity/pokemon/metapod/rig/zzz/summon/as_node/eyelid_right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eyelid_right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.metapod.rig.node.eye_right1] run function ssbrc:entity/pokemon/metapod/rig/zzz/summon/as_node/eye_right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye_right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.metapod.rig.node.eyelid_left1] run function ssbrc:entity/pokemon/metapod/rig/zzz/summon/as_node/eyelid_left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eyelid_left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.metapod.rig.node.eye_left1] run function ssbrc:entity/pokemon/metapod/rig/zzz/summon/as_node/eye_left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye_left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.metapod.rig.node.body1] run function ssbrc:entity/pokemon/metapod/rig/zzz/summon/as_node/body1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body1 set from storage animated_java:gu out
function ssbrc:entity/pokemon/metapod/rig/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function ssbrc:entity/pokemon/metapod/rig/zzz/summon/variant_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function ssbrc:entity/pokemon/metapod/rig/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
execute at @s run function ssbrc:entity/pokemon/metapod/rig/zzz/summon/on_summon/rig
tag @s remove aj.new
execute on passengers run tag @s remove aj.new
execute on passengers run ride @s dismount