# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'b989c4dda4ce5ee0252009d4abf26197ac41bf0781fc1ddd9c1db7ed0187f96a'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack