# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tyrogue/animations/ground_idle/zzz/apply_frame {frame: 1}
scoreboard players add @s aj.ground_idle.frame 1