# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute if function ssbrc:entity/pokemon/snorlax/rig/variants/$(variant)/apply run return 1
return fail