# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(eyelid_left1) ~ ~ ~ ~ ~
$execute as $(eyelid_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eye_left1) ~ ~ ~ ~ ~
$execute as $(eye_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eyelid_right1) ~ ~ ~ ~ ~
$execute as $(eyelid_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eye_right1) ~ ~ ~ ~ ~
$execute as $(eye_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(mouth_open1) ~ ~ ~ ~ ~
$execute as $(mouth_open1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(mouth_closed1) ~ ~ ~ ~ ~
$execute as $(mouth_closed1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(stem_left1) ~ ~ ~ ~ ~
$execute as $(stem_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(stem_right1) ~ ~ ~ ~ ~
$execute as $(stem_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(head1) ~ ~ ~ ~ ~
$execute as $(head1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leaf_left1) ~ ~ ~ ~ ~
$execute as $(leaf_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(finger_left1) ~ ~ ~ ~ ~
$execute as $(finger_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leaf_left4) ~ ~ ~ ~ ~
$execute as $(leaf_left4) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(finger_left4) ~ ~ ~ ~ ~
$execute as $(finger_left4) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leaf_left5) ~ ~ ~ ~ ~
$execute as $(leaf_left5) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(finger_left5) ~ ~ ~ ~ ~
$execute as $(finger_left5) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(arm_left3) ~ ~ ~ ~ ~
$execute as $(arm_left3) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(arm_left1) ~ ~ ~ ~ ~
$execute as $(arm_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leaf_right1) ~ ~ ~ ~ ~
$execute as $(leaf_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(finger_right1) ~ ~ ~ ~ ~
$execute as $(finger_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leaf_right4) ~ ~ ~ ~ ~
$execute as $(leaf_right4) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(finger_right4) ~ ~ ~ ~ ~
$execute as $(finger_right4) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leaf_right5) ~ ~ ~ ~ ~
$execute as $(leaf_right5) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(finger_right5) ~ ~ ~ ~ ~
$execute as $(finger_right5) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(arm_right3) ~ ~ ~ ~ ~
$execute as $(arm_right3) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(arm_right1) ~ ~ ~ ~ ~
$execute as $(arm_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(torso3) ~ ~ ~ ~ ~
$execute as $(torso3) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(torso1) ~ ~ ~ ~ ~
$execute as $(torso1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(foot_left1) ~ ~ ~ ~ ~
$execute as $(foot_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_left3) ~ ~ ~ ~ ~
$execute as $(leg_left3) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_left1) ~ ~ ~ ~ ~
$execute as $(leg_left1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(foot_right1) ~ ~ ~ ~ ~
$execute as $(foot_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_right3) ~ ~ ~ ~ ~
$execute as $(leg_right3) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_right1) ~ ~ ~ ~ ~
$execute as $(leg_right1) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1