# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
execute unless data storage animated_java:temp {entry:{data:{rig_hash: '32d14e5ebdb8063b34247ad277286d09d068cf847f96f248adeb4365b93a84a2'}}} run function animated_java:global/remove/outdated_rig
function ssbrc:entity/pokemon/lapras/rig/remove/this/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
function animated_java:global/remove/entity_stack