# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.tornado.root] run return 0
execute on passengers if entity @s[tag=aj.tornado.data] unless data entity @s {data:{rigHash: '22192ca6f459f3c4aea40572e9347b433815a3ff4f16a3b62d845a81b3e61dca'}} on vehicle run function animated_java:tornado/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1