# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "ssbrc:entity/pokemon/snorlax/rig"
data modify storage animated_java:temp entry.data.rig_hash set value "7d05d2717a0616b87464a35fb26a00181146de29a774e7412d83091ee3ab0f4f"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.belly3] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/belly3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.belly3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.belly1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/belly1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.belly1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.eye_right1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/eye_right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye_right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.eye_happy_right1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/eye_happy_right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye_happy_right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.eye_sad_right1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/eye_sad_right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye_sad_right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.eye_wide_right1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/eye_wide_right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye_wide_right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.eye_left1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/eye_left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye_left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.eye_happy_left1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/eye_happy_left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye_happy_left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.eye_sad_left1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/eye_sad_left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye_sad_left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.eye_wide_left1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/eye_wide_left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye_wide_left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.mouth_closed1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/mouth_closed1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mouth_closed1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.mouth_closed_happy1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/mouth_closed_happy1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mouth_closed_happy1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.mouth_closed_sad1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/mouth_closed_sad1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mouth_closed_sad1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.mouth_open1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/mouth_open1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mouth_open1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.mouth_open_happy1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/mouth_open_happy1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mouth_open_happy1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.ear_right1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/ear_right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ear_right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.ear_left1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/ear_left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ear_left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.head1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/head1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.neck1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/neck1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.neck1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.finger_pinky_right1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/finger_pinky_right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.finger_pinky_right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.finger_ring_right1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/finger_ring_right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.finger_ring_right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.finger_middle_right1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/finger_middle_right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.finger_middle_right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.finger_index_right1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/finger_index_right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.finger_index_right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.finger_thumb_right1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/finger_thumb_right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.finger_thumb_right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.arm_right3] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/arm_right3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.arm_right3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.arm_right1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/arm_right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.arm_right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.finger_pinky_left1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/finger_pinky_left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.finger_pinky_left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.finger_ring_left1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/finger_ring_left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.finger_ring_left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.finger_middle_left1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/finger_middle_left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.finger_middle_left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.finger_index_left1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/finger_index_left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.finger_index_left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.finger_thumb_left1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/finger_thumb_left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.finger_thumb_left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.arm_left3] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/arm_left3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.arm_left3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.arm_left1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/arm_left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.arm_left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.toe_inner_right1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/toe_inner_right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.toe_inner_right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.toe_middle_right1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/toe_middle_right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.toe_middle_right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.toe_outer_right1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/toe_outer_right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.toe_outer_right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.foot_right1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/foot_right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.foot_right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.leg_right1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/leg_right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg_right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.toe_inner_left1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/toe_inner_left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.toe_inner_left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.toe_middle_left1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/toe_middle_left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.toe_middle_left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.toe_outer_left1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/toe_outer_left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.toe_outer_left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.foot_left1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/foot_left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.foot_left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.entity.pokemon.snorlax.rig.node.leg_left1] run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/as_node/leg_left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg_left1 set from storage animated_java:gu out
function ssbrc:entity/pokemon/snorlax/rig/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/variant_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
execute at @s run function ssbrc:entity/pokemon/snorlax/rig/zzz/summon/on_summon/rig
tag @s remove aj.new
execute on passengers run tag @s remove aj.new
execute on passengers run ride @s dismount