# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tyrogue/animations/animation_tyrogue_ground_walk/zzz/apply_frame {frame: 80}
scoreboard players add @s aj.animation_tyrogue_ground_walk.frame 1