# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=ssbrc.entity.pokemon.lapras.rig.animation.surfacewater_idle.playing] run function ssbrc:entity/pokemon/lapras/rig/animations/surfacewater_idle/zzz/on_tick
particle minecraft:cloud ~ ~.5 ~ .5 .1 .5 0 5 normal @a