# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s temp matches 1.. run return run function ssbrc:game/entity/npc/pokemon/gyarados/logic/tick
execute if predicate ssbrc:random_chance/0.15 run function ssbrc:game/entity/npc/pokemon/gyarados/logic/activate
execute if entity @s[tag=ssbrc.entity.pokemon.gyarados.rig.animation.water_idle.playing] run function ssbrc:game/entity/npc/pokemon/gyarados/rig/animations/water_idle/zzz/on_tick
execute if entity @s[tag=ssbrc.entity.pokemon.gyarados.rig.animation.surfacewater_idle.playing] run function ssbrc:game/entity/npc/pokemon/gyarados/rig/animations/surfacewater_idle/zzz/on_tick
execute if entity @s[tag=ssbrc.entity.pokemon.gyarados.rig.animation.surfacewater_swim.playing] run function ssbrc:game/entity/npc/pokemon/gyarados/rig/animations/surfacewater_swim/zzz/on_tick
function ssbrc:game/entity/npc/pokemon/gyarados/rig/root/on_tick/transform_floating_entities
function ssbrc:game/entity/npc/pokemon/gyarados/rig/root/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
