# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.shell2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_shell2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.shell] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_shell set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.pupil_right2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_pupil_right2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.pupil_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_pupil_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.eyelid_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eyelid_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.eye_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eye_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.pupil_left2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_pupil_left2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.pupil_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_pupil_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.eyelid_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eyelid_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.eye_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eye_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.muzzle2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_muzzle2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.muzzle] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_muzzle set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.tongue] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tongue set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.jaw] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_jaw set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.ear_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_ear_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.ear_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_ear_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.head_angle] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head_angle set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.neck3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_neck3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.neck2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_neck2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.chest2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_chest2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.chest] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_chest set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.tail2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.tail] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.torso] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_torso set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.leg_front_left4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_front_left4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.leg_front_left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_front_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.leg_front_left2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_front_left2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.leg_front_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_front_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.leg_back_left4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_back_left4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.leg_back_left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_back_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.leg_back_left2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_back_left2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.leg_back_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_back_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.leg_front_right4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_front_right4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.leg_front_right3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_front_right3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.leg_front_right2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_front_right2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.leg_front_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_front_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.leg_back_right4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_back_right4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.leg_back_right3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_back_right3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.leg_back_right2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_back_right2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.lapras.node.leg_back_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_back_right set from storage aj:uuid main.out