# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage ssbrc:entity/pokemon/abra/rig rig_hash set value 'fad5a7c28f1c447ab8b7b971f17f0d639b5c30323b615f73e0d1d72b3d74843c'
scoreboard objectives add aj.ground_idle.frame dummy