# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.sudowoodo.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'sudowoodo', 'function_path': 'animated_java:sudowoodo/variants/default/apply'}
execute on passengers if entity @s[tag=aj.sudowoodo.bone.eyelid_left1] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_eyelid_left1
execute on passengers if entity @s[tag=aj.sudowoodo.bone.eye_left1] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_eye_left1
execute on passengers if entity @s[tag=aj.sudowoodo.bone.eyelid_right1] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_eyelid_right1
execute on passengers if entity @s[tag=aj.sudowoodo.bone.eye_right1] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_eye_right1
execute on passengers if entity @s[tag=aj.sudowoodo.bone.mouth_open1] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_mouth_open1
execute on passengers if entity @s[tag=aj.sudowoodo.bone.mouth_closed1] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_mouth_closed1
execute on passengers if entity @s[tag=aj.sudowoodo.bone.stem_left1] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_stem_left1
execute on passengers if entity @s[tag=aj.sudowoodo.bone.stem_right1] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_stem_right1
execute on passengers if entity @s[tag=aj.sudowoodo.bone.head1] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_head1
execute on passengers if entity @s[tag=aj.sudowoodo.bone.leaf_left1] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_leaf_left1
execute on passengers if entity @s[tag=aj.sudowoodo.bone.finger_left1] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_finger_left1
execute on passengers if entity @s[tag=aj.sudowoodo.bone.leaf_left4] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_leaf_left4
execute on passengers if entity @s[tag=aj.sudowoodo.bone.finger_left4] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_finger_left4
execute on passengers if entity @s[tag=aj.sudowoodo.bone.leaf_left5] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_leaf_left5
execute on passengers if entity @s[tag=aj.sudowoodo.bone.finger_left5] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_finger_left5
execute on passengers if entity @s[tag=aj.sudowoodo.bone.arm_left3] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_arm_left3
execute on passengers if entity @s[tag=aj.sudowoodo.bone.arm_left1] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_arm_left1
execute on passengers if entity @s[tag=aj.sudowoodo.bone.leaf_right1] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_leaf_right1
execute on passengers if entity @s[tag=aj.sudowoodo.bone.finger_right1] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_finger_right1
execute on passengers if entity @s[tag=aj.sudowoodo.bone.leaf_right4] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_leaf_right4
execute on passengers if entity @s[tag=aj.sudowoodo.bone.finger_right4] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_finger_right4
execute on passengers if entity @s[tag=aj.sudowoodo.bone.leaf_right5] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_leaf_right5
execute on passengers if entity @s[tag=aj.sudowoodo.bone.finger_right5] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_finger_right5
execute on passengers if entity @s[tag=aj.sudowoodo.bone.arm_right3] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_arm_right3
execute on passengers if entity @s[tag=aj.sudowoodo.bone.arm_right1] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_arm_right1
execute on passengers if entity @s[tag=aj.sudowoodo.bone.torso3] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_torso3
execute on passengers if entity @s[tag=aj.sudowoodo.bone.torso1] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_torso1
execute on passengers if entity @s[tag=aj.sudowoodo.bone.foot_left1] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_foot_left1
execute on passengers if entity @s[tag=aj.sudowoodo.bone.leg_left3] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_leg_left3
execute on passengers if entity @s[tag=aj.sudowoodo.bone.leg_left1] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_leg_left1
execute on passengers if entity @s[tag=aj.sudowoodo.bone.foot_right1] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_foot_right1
execute on passengers if entity @s[tag=aj.sudowoodo.bone.leg_right3] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_leg_right3
execute on passengers if entity @s[tag=aj.sudowoodo.bone.leg_right1] run function animated_java:sudowoodo/variants/default/zzz/apply_to_bone_leg_right1
return 1