# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tyrogue/animations/pause_all
tag @s add aj.tyrogue.animation.animation_tyrogue_shoulder_left.playing
scoreboard players set @s aj.animation_tyrogue_shoulder_left.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:tyrogue/animations/animation_tyrogue_shoulder_left/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only