# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.beat.root] run return 0
execute on passengers if entity @s[tag=aj.beat.data] unless data entity @s {data:{rigHash: 'e7a07d72bd88a3ece34af11649486fb6a97a28ca3d760713133cc08f1f0a76d6'}} on vehicle run function animated_java:beat/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1