# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.pokemon_lapras.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:pokemon_lapras/as_root/pre_tick
execute if entity @s[tag=aj.pokemon_lapras.animation.animation_lapras_surfacewater_idle.playing] run function animated_java:pokemon_lapras/animations/animation_lapras_surfacewater_idle/zzz/on_tick
execute on passengers if entity @s[tag=aj.pokemon_lapras.data] run function animated_java:pokemon_lapras/root/zzz/1
execute at @s on passengers run rotate @s ~ ~
particle minecraft:cloud ~ ~-1 ~ 0.75 0.1 0.75 0.0 15 normal @a
function #animated_java:pokemon_lapras/as_root/post_tick