# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'fb7392741fb5bd689cf5fbc9d3797bfee0d91b39a6f5bf522f0c518791fcf34e'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack