# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage ssbrc:entity/pokemon/magnemite/rig rig_hash set value '61fde3bc18a61d9429279b04dd17a34a7eb80a72367231bbae6d8e7387e178d0'
scoreboard objectives add aj.air_idle.frame dummy