# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.ground_idle.frame dummy
scoreboard objectives add aj.animation_sudowoodo_blink.frame dummy
scoreboard objectives add aj.animation_sudowoodo_cry.frame dummy