# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(closed_mouth_left1) {transformation: [1f,0f,0f,-0.3311f,0f,0.9968f,0.0799f,0.5178f,0f,-0.0799f,0.9968f,-0.3003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(closed_mouth_right1) {transformation: [1f,0f,0f,0.2314f,0f,0.9968f,0.0799f,0.5178f,0f,-0.0799f,0.9968f,-0.3003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(closed_mouth1) {transformation: [1f,0f,0f,0.0127f,0f,0.9968f,0.0799f,0.4867f,0f,-0.0799f,0.9968f,-0.2978f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouth_half_open1) {transformation: [1f,0f,0f,-0.0498f,0f,0.9968f,0.0799f,0.4555f,0f,-0.0799f,0.9968f,-0.2953f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouth_full_open1) {transformation: [1f,0f,0f,-0.0498f,0f,0.9968f,0.0799f,0.5339f,0f,-0.0799f,0.9968f,-0.2953f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tougue9) {transformation: [0f,0f,0f,-0.0498f,0f,0f,0f,0.4549f,0f,0f,0f,-0.1071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tougue8) {transformation: [0f,0f,0f,-0.0498f,0f,0f,0f,0.4549f,0f,0f,0f,-0.1071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tougue7) {transformation: [0f,0f,0f,-0.0498f,0f,0f,0f,0.4549f,0f,0f,0f,-0.1071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tougue6) {transformation: [0f,0f,0f,-0.0498f,0f,0f,0f,0.4549f,0f,0f,0f,-0.1071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tougue1) {transformation: [0f,0f,0f,-0.0498f,0f,0f,0f,0.4549f,0f,0f,0f,-0.1071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouth_tongue_full_open1) {transformation: [1f,0f,0f,-0.0498f,0f,0.9968f,0.0799f,0.4716f,0f,-0.0799f,0.9968f,-0.2903f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(blush_right1) {transformation: [1f,0f,0f,0.2877f,0f,0.9968f,0.0799f,0.5434f,0f,-0.0799f,0.9968f,-0.1769f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(blush_left1) {transformation: [1f,0f,0f,-0.3873f,0f,0.9968f,0.0799f,0.5434f,0f,-0.0799f,0.9968f,-0.1769f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_eye_rotation1) {transformation: [1f,0f,0f,-0.1592f,0f,0.9993f,0.0363f,0.673f,0f,-0.0363f,0.9993f,-0.3311f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_angry_eye1) {transformation: [1f,0f,0f,0.0283f,0f,0.9993f,0.0363f,0.6304f,0f,-0.0363f,0.9993f,-0.2107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_pupil1) {transformation: [1f,0f,0f,-0.2529f,0f,0.9993f,0.0363f,0.704f,0f,-0.0363f,0.9993f,-0.3385f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_pupil_closed3) {transformation: [1f,0f,0f,-0.2373f,0f,0.9993f,0.0363f,0.673f,0f,-0.0363f,0.9993f,-0.3311f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_pupil_closed1) {transformation: [1f,0f,0f,-0.3311f,0f,0.9993f,0.0363f,0.7042f,0f,-0.0363f,0.9993f,-0.3322f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_eye_rotation1) {transformation: [1f,0f,0f,0.0596f,0f,0.9993f,0.0363f,0.673f,0f,-0.0363f,0.9993f,-0.3311f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_angry_eye1) {transformation: [1f,0f,0f,-0.1279f,0f,0.9993f,0.0363f,0.6304f,0f,-0.0363f,0.9993f,-0.2107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_pupil1) {transformation: [1f,0f,0f,0.1533f,0f,0.9993f,0.0363f,0.704f,0f,-0.0363f,0.9993f,-0.3385f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_pupil_closed3) {transformation: [1f,0f,0f,0.1377f,0f,0.9993f,0.0363f,0.673f,0f,-0.0363f,0.9993f,-0.3311f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_pupil_closed1) {transformation: [1f,0f,0f,0.2314f,0f,0.9993f,0.0363f,0.7042f,0f,-0.0363f,0.9993f,-0.3322f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso1) {transformation: [1f,0f,0f,-0.0498f,0f,0.9968f,0.0799f,0.6829f,0f,-0.0799f,0.9968f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"gas":{"px":-0.04981146414322312,"py":0.5783155005466568,"pz":0.2591865198474389,"ry":360,"rx":85.41811385307074}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args