# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(closed_mouth_left1) {transformation: [1f,-0.007f,-0.0003f,-0.3251f,0.007f,0.9992f,0.0405f,0.5456f,0f,-0.0405f,0.9992f,-0.3065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(closed_mouth_right1) {transformation: [1f,-0.007f,-0.0003f,0.2374f,0.007f,0.9992f,0.0405f,0.5495f,0f,-0.0405f,0.9992f,-0.3065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(closed_mouth1) {transformation: [1f,-0.007f,-0.0003f,0.0189f,0.007f,0.9992f,0.0405f,0.5168f,0f,-0.0405f,0.9992f,-0.3053f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouth_half_open1) {transformation: [1f,-0.007f,-0.0003f,-0.0434f,0.007f,0.9992f,0.0405f,0.4851f,0f,-0.0405f,0.9992f,-0.304f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouth_full_open1) {transformation: [1f,-0.007f,-0.0003f,-0.044f,0.007f,0.9992f,0.0405f,0.5634f,0f,-0.0405f,0.9992f,-0.3009f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tougue9) {transformation: [0f,0f,0f,-0.0434f,0f,0f,0f,0.4771f,0f,0f,0f,-0.116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tougue8) {transformation: [0f,0f,0f,-0.0434f,0f,0f,0f,0.4771f,0f,0f,0f,-0.116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tougue7) {transformation: [0f,0f,0f,-0.0434f,0f,0f,0f,0.4771f,0f,0f,0f,-0.116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tougue6) {transformation: [0f,0f,0f,-0.0434f,0f,0f,0f,0.4771f,0f,0f,0f,-0.116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(tougue1) {transformation: [0f,0f,0f,-0.0434f,0f,0f,0f,0.4771f,0f,0f,0f,-0.116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouth_tongue_full_open1) {transformation: [1f,-0.007f,-0.0003f,-0.0435f,0.007f,0.9992f,0.0405f,0.501f,0f,-0.0405f,0.9992f,-0.2984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(blush_right1) {transformation: [1f,-0.007f,-0.0003f,0.2935f,0.007f,0.9992f,0.0405f,0.5706f,0f,-0.0405f,0.9992f,-0.1823f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(blush_left1) {transformation: [1f,-0.007f,-0.0003f,-0.3815f,0.007f,0.9992f,0.0405f,0.5659f,0f,-0.0405f,0.9992f,-0.1823f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_eye_rotation1) {transformation: [1f,-0.007f,0f,-0.1543f,0.007f,1f,-0.0031f,0.703f,0f,0.0031f,1f,-0.3312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_angry_eye1) {transformation: [1f,-0.007f,0f,0.0335f,0.007f,1f,-0.0031f,0.6571f,0f,0.0031f,1f,-0.2126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_pupil1) {transformation: [1f,-0.007f,0f,-0.2483f,0.007f,1f,-0.0031f,0.7336f,0f,0.0031f,1f,-0.3374f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_pupil_closed3) {transformation: [1f,-0.007f,0f,-0.2325f,0.007f,1f,-0.0031f,0.7025f,0f,0.0031f,1f,-0.3312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_pupil_closed1) {transformation: [1f,-0.007f,0f,-0.3264f,0.007f,1f,-0.0031f,0.7331f,0f,0.0031f,1f,-0.3311f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_eye_rotation1) {transformation: [1f,-0.007f,0f,0.0644f,0.007f,1f,-0.0031f,0.7046f,0f,0.0031f,1f,-0.3312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_angry_eye1) {transformation: [1f,-0.007f,0f,-0.1228f,0.007f,1f,-0.0031f,0.656f,0f,0.0031f,1f,-0.2126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_pupil1) {transformation: [1f,-0.007f,0f,0.1579f,0.007f,1f,-0.0031f,0.7365f,0f,0.0031f,1f,-0.3374f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_pupil_closed3) {transformation: [1f,-0.007f,0f,0.1425f,0.007f,1f,-0.0031f,0.7051f,0f,0.0031f,1f,-0.3312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_pupil_closed1) {transformation: [1f,-0.007f,0f,0.2361f,0.007f,1f,-0.0031f,0.737f,0f,0.0031f,1f,-0.3311f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso1) {transformation: [1f,-0.007f,-0.0003f,-0.0449f,0.007f,0.9992f,0.0405f,0.7007f,0f,-0.0405f,0.9992f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"gas":{"px":-0.04413438808194969,"py":0.5859597744326744,"pz":0.25486211919988394,"ry":350.2372819199609,"rx":87.64236128226288}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args