# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:lapras/animations/surfacewater_idle/zzz/apply_frame {frame: 156}
scoreboard players add @s aj.surfacewater_idle.frame 1