# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.dugtrio.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'dugtrio', 'function_path': 'animated_java:dugtrio/variants/shiny/apply'}
execute on passengers if entity @s[tag=aj.dugtrio.bone.nose4] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_nose4
execute on passengers if entity @s[tag=aj.dugtrio.bone.pupil_left4] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_pupil_left4
execute on passengers if entity @s[tag=aj.dugtrio.bone.eyelid_left4] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_eyelid_left4
execute on passengers if entity @s[tag=aj.dugtrio.bone.eye_left4] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_eye_left4
execute on passengers if entity @s[tag=aj.dugtrio.bone.pupil_right4] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_pupil_right4
execute on passengers if entity @s[tag=aj.dugtrio.bone.eyelid_right4] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_eyelid_right4
execute on passengers if entity @s[tag=aj.dugtrio.bone.eye_right4] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_eye_right4
execute on passengers if entity @s[tag=aj.dugtrio.bone.body1_3] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_body1_3
execute on passengers if entity @s[tag=aj.dugtrio.bone.body5] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_body5
execute on passengers if entity @s[tag=aj.dugtrio.bone.ground4] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_ground4
execute on passengers if entity @s[tag=aj.dugtrio.bone.nose5] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_nose5
execute on passengers if entity @s[tag=aj.dugtrio.bone.pupil_left5] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_pupil_left5
execute on passengers if entity @s[tag=aj.dugtrio.bone.eyelid_left5] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_eyelid_left5
execute on passengers if entity @s[tag=aj.dugtrio.bone.eye_left5] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_eye_left5
execute on passengers if entity @s[tag=aj.dugtrio.bone.pupil_right5] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_pupil_right5
execute on passengers if entity @s[tag=aj.dugtrio.bone.eyelid_right5] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_eyelid_right5
execute on passengers if entity @s[tag=aj.dugtrio.bone.eye_right5] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_eye_right5
execute on passengers if entity @s[tag=aj.dugtrio.bone.body6] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_body6
execute on passengers if entity @s[tag=aj.dugtrio.bone.ground5] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_ground5
execute on passengers if entity @s[tag=aj.dugtrio.bone.nose6] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_nose6
execute on passengers if entity @s[tag=aj.dugtrio.bone.pupil_left6] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_pupil_left6
execute on passengers if entity @s[tag=aj.dugtrio.bone.eyelid_left6] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_eyelid_left6
execute on passengers if entity @s[tag=aj.dugtrio.bone.eye_left6] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_eye_left6
execute on passengers if entity @s[tag=aj.dugtrio.bone.pupil_right6] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_pupil_right6
execute on passengers if entity @s[tag=aj.dugtrio.bone.eyelid_right6] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_eyelid_right6
execute on passengers if entity @s[tag=aj.dugtrio.bone.eye_right6] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_eye_right6
execute on passengers if entity @s[tag=aj.dugtrio.bone.body3_3] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_body3_3
execute on passengers if entity @s[tag=aj.dugtrio.bone.body7] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_body7
execute on passengers if entity @s[tag=aj.dugtrio.bone.ground6] run function animated_java:dugtrio/variants/shiny/zzz/apply_to_bone_ground6
return 1