# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(mouth) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.3733f,0f,0f,-1f,0.3573f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_wing) {transformation: [-0.9623f,0.2719f,0f,-0.3875f,0.2719f,0.9623f,0f,-0.2204f,0f,0f,-1f,-0.0781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_wing) {transformation: [-0.9623f,-0.2719f,0f,0.3875f,-0.2719f,0.9623f,0f,-0.2204f,0f,0f,-1f,-0.0781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(beat) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.0954f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}