# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,0.2688f,0f,1f,0f,-0.1942f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,0.2688f,0f,1f,0f,-0.1942f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.3972f,0f,0f,-1f,0.3573f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-0.8891f,0.4577f,0f,-0.3875f,0.4577f,0.8891f,0f,-0.2442f,0f,0f,-1f,-0.0781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-0.8891f,-0.4577f,0f,0.3875f,-0.4577f,0.8891f,0f,-0.2442f,0f,0f,-1f,-0.0781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_beat) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1192f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}