# player adv logic for getting bit 15 at value 0. Generated by generate_files.py in Reeling Rods in GM4.
# run from advancement bits/bit_15_0

advancement revoke @s only hooked_entity_lib:bits/bit_15_0

execute if entity @s[gamemode=adventure] run return fail

data modify storage hooked_entity_lib:temp bit_data set value {bit_score:"hooked_entity_lib.id_bit.15=0",bit:"15"}
data modify storage hooked_entity_lib:temp bit_data.UUID set from entity @s UUID
function hooked_entity_lib:player/received_bit with storage hooked_entity_lib:temp bit_data
