# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify entity $(nose1) interpolation_duration set value 1
$data modify entity $(pupil_left1) interpolation_duration set value 1
$data modify entity $(eyelid_left1) interpolation_duration set value 1
$data modify entity $(eye_left1) interpolation_duration set value 1
$data modify entity $(pupil_right1) interpolation_duration set value 1
$data modify entity $(eyelid_right1) interpolation_duration set value 1
$data modify entity $(eye_right1) interpolation_duration set value 1
$data modify entity $(body3) interpolation_duration set value 1
$data modify entity $(body1) interpolation_duration set value 1
$data modify entity $(ground1) interpolation_duration set value 1