# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:pokemon_lapras/animations/animation_lapras_surfacewater_idle/zzz/apply_frame {frame: 1}
scoreboard players add @s aj.animation_lapras_surfacewater_idle.frame 1