# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.tail7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.tail6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.tail5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.tail1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.pad_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_pad_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.pad_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_pad_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.jaw1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_jaw1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.eye_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eye_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.eye_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_eye_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.ear_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_ear_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.ear_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_ear_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.head1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.finger_index_right3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_finger_index_right3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.finger_index_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_finger_index_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.finger_middle_right3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_finger_middle_right3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.finger_middle_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_finger_middle_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.finger_pinky_right3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_finger_pinky_right3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.finger_pinky_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_finger_pinky_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.forearm_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_forearm_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.arm_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_arm_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.finger_index_left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_finger_index_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.finger_index_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_finger_index_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.finger_middle_left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_finger_middle_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.finger_middle_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_finger_middle_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.finger_pinky_left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_finger_pinky_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.finger_pinky_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_finger_pinky_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.forearm_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_forearm_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.arm_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_arm_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.chest1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_chest1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.torso1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_torso1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.toe_outer_right3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_toe_outer_right3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.toe_outer_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_toe_outer_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.toe_inner_right3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_toe_inner_right3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.toe_inner_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_toe_inner_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.toe_back_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_toe_back_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.foot_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_foot_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.knee_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_knee_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.leg_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.toe_outer_left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_toe_outer_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.toe_outer_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_toe_outer_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.toe_inner_left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_toe_inner_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.toe_inner_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_toe_inner_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.toe_back_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_toe_back_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.foot_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_foot_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.knee_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_knee_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.abra.node.leg_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_left1 set from storage aj:uuid main.out