# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:slowpoke rig_hash set value 'e936fe02331da9558196737ad0aa47db402f031155e2123ca9b8dd3f51d083f8'
scoreboard objectives add aj.floor_idle.frame dummy
scoreboard objectives add aj.sleep.frame dummy