# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.magnemite.root] run return 0
execute if entity @s[tag=aj.magnemite.animation.air_idle.playing] run function animated_java:magnemite/animations/air_idle/zzz/on_tick