# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(pupil1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(pupil_closed1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(eye1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(nail_head1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(nail_left_rotation1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(nail_right_rotation1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(magnet_left1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(magnet_right1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(body1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i