# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gyarados/animations/pause_all
tag @s add aj.gyarados.animation.surfacewater_swim.playing
scoreboard players set @s aj.surfacewater_swim.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:gyarados/animations/surfacewater_swim/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only