# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.ground_idle.frame dummy
scoreboard objectives add aj.shoulder_right.frame dummy
scoreboard objectives add aj.shoulder_left.frame dummy
scoreboard objectives add aj.physical.frame dummy