# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(shell2) ~ ~ ~ ~ ~
$execute as $(shell2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(shell) ~ ~ ~ ~ ~
$execute as $(shell) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(pupil_right2) ~ ~ ~ ~ ~
$execute as $(pupil_right2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(pupil_right) ~ ~ ~ ~ ~
$execute as $(pupil_right) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eyelid_right) ~ ~ ~ ~ ~
$execute as $(eyelid_right) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eye_right) ~ ~ ~ ~ ~
$execute as $(eye_right) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(pupil_left2) ~ ~ ~ ~ ~
$execute as $(pupil_left2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(pupil_left) ~ ~ ~ ~ ~
$execute as $(pupil_left) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eyelid_left) ~ ~ ~ ~ ~
$execute as $(eyelid_left) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(eye_left) ~ ~ ~ ~ ~
$execute as $(eye_left) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(muzzle2) ~ ~ ~ ~ ~
$execute as $(muzzle2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(muzzle) ~ ~ ~ ~ ~
$execute as $(muzzle) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(tongue) ~ ~ ~ ~ ~
$execute as $(tongue) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(jaw) ~ ~ ~ ~ ~
$execute as $(jaw) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(ear_left) ~ ~ ~ ~ ~
$execute as $(ear_left) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(ear_right) ~ ~ ~ ~ ~
$execute as $(ear_right) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(head_angle) ~ ~ ~ ~ ~
$execute as $(head_angle) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(neck3) ~ ~ ~ ~ ~
$execute as $(neck3) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(neck2) ~ ~ ~ ~ ~
$execute as $(neck2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(chest2) ~ ~ ~ ~ ~
$execute as $(chest2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(chest) ~ ~ ~ ~ ~
$execute as $(chest) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(tail2) ~ ~ ~ ~ ~
$execute as $(tail2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(tail) ~ ~ ~ ~ ~
$execute as $(tail) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(torso) ~ ~ ~ ~ ~
$execute as $(torso) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_front_left4) ~ ~ ~ ~ ~
$execute as $(leg_front_left4) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_front_left3) ~ ~ ~ ~ ~
$execute as $(leg_front_left3) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_front_left2) ~ ~ ~ ~ ~
$execute as $(leg_front_left2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_front_left) ~ ~ ~ ~ ~
$execute as $(leg_front_left) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_back_left4) ~ ~ ~ ~ ~
$execute as $(leg_back_left4) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_back_left3) ~ ~ ~ ~ ~
$execute as $(leg_back_left3) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_back_left2) ~ ~ ~ ~ ~
$execute as $(leg_back_left2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_back_left) ~ ~ ~ ~ ~
$execute as $(leg_back_left) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_front_right4) ~ ~ ~ ~ ~
$execute as $(leg_front_right4) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_front_right3) ~ ~ ~ ~ ~
$execute as $(leg_front_right3) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_front_right2) ~ ~ ~ ~ ~
$execute as $(leg_front_right2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_front_right) ~ ~ ~ ~ ~
$execute as $(leg_front_right) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_back_right4) ~ ~ ~ ~ ~
$execute as $(leg_back_right4) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_back_right3) ~ ~ ~ ~ ~
$execute as $(leg_back_right3) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_back_right2) ~ ~ ~ ~ ~
$execute as $(leg_back_right2) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1
$tp $(leg_back_right) ~ ~ ~ ~ ~
$execute as $(leg_back_right) store success entity @s OnGround byte 1 store success score @s aj.i unless score @s aj.i matches 1