# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:sudowoodo rig_hash set value '183fe7b891e19d830bfc90d177eaf404a0d15ead37416dc0f51cd7ffe42ebfec'
scoreboard objectives add aj.ground_idle.frame dummy
scoreboard objectives add aj.animation_sudowoodo_blink.frame dummy
scoreboard objectives add aj.animation_sudowoodo_cry.frame dummy