# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function ssbrc:entity/pokemon/snorlax/rig/animations/pause_all
scoreboard players set @s aj.sleep.frame 0
tag @s add aj.transforms_only
execute at @s run function ssbrc:entity/pokemon/snorlax/rig/animations/sleep/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only