# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=ssbrc.fighter.mega_man.beat_call.rig.animation.idle.playing] run function ssbrc:fighter/mega_man/beat_call/rig/animations/idle/zzz/on_tick
execute if entity @s[tag=ssbrc.fighter.mega_man.beat_call.rig.animation.attack.playing] run function ssbrc:fighter/mega_man/beat_call/rig/animations/attack/zzz/on_tick
function ssbrc:fighter/mega_man/beat_call/rig/root/zzz/0 with storage animated_java:temp entry.data.uuids_by_name