# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.metapod.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'metapod', 'function_path': 'animated_java:metapod/variants/shiny/apply'}
execute on passengers if entity @s[tag=aj.metapod.bone.body_segment3] run function animated_java:metapod/variants/shiny/zzz/apply_to_bone_body_segment3
execute on passengers if entity @s[tag=aj.metapod.bone.body_segment1] run function animated_java:metapod/variants/shiny/zzz/apply_to_bone_body_segment1
execute on passengers if entity @s[tag=aj.metapod.bone.eyelid_right1] run function animated_java:metapod/variants/shiny/zzz/apply_to_bone_eyelid_right1
execute on passengers if entity @s[tag=aj.metapod.bone.eye_right1] run function animated_java:metapod/variants/shiny/zzz/apply_to_bone_eye_right1
execute on passengers if entity @s[tag=aj.metapod.bone.eyelid_left1] run function animated_java:metapod/variants/shiny/zzz/apply_to_bone_eyelid_left1
execute on passengers if entity @s[tag=aj.metapod.bone.eye_left1] run function animated_java:metapod/variants/shiny/zzz/apply_to_bone_eye_left1
execute on passengers if entity @s[tag=aj.metapod.bone.body1] run function animated_java:metapod/variants/shiny/zzz/apply_to_bone_body1
return 1