# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.root
function ssbrc:entity/pokemon/lapras/rig/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.target
function ssbrc:entity/pokemon/lapras/rig/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.body
function ssbrc:entity/pokemon/lapras/rig/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.head
function ssbrc:entity/pokemon/lapras/rig/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.mouth
function ssbrc:entity/pokemon/lapras/rig/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.special
function ssbrc:entity/pokemon/lapras/rig/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.face
function ssbrc:entity/pokemon/lapras/rig/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.eye1
function ssbrc:entity/pokemon/lapras/rig/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.eye2
function ssbrc:entity/pokemon/lapras/rig/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.horn
function ssbrc:entity/pokemon/lapras/rig/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.physical
function ssbrc:entity/pokemon/lapras/rig/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.jaw_upper
function ssbrc:entity/pokemon/lapras/rig/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.jaw_lower
function ssbrc:entity/pokemon/lapras/rig/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.tail_tip
function ssbrc:entity/pokemon/lapras/rig/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.locator5
function ssbrc:entity/pokemon/lapras/rig/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.locator6
function ssbrc:entity/pokemon/lapras/rig/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args