# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.sleep.frame matches 2.. run scoreboard players set @s aj.sleep.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.sleep.frame
execute at @s run function animated_java:snorlax/animations/sleep/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.sleep.frame 1