# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify entity $(tail7) start_interpolation set value -1
$data modify entity $(tail6) start_interpolation set value -1
$data modify entity $(tail5) start_interpolation set value -1
$data modify entity $(tail1) start_interpolation set value -1
$data modify entity $(ear_left1) start_interpolation set value -1
$data modify entity $(ear_right1) start_interpolation set value -1
$data modify entity $(eyelid_left1) start_interpolation set value -1
$data modify entity $(eye_left1) start_interpolation set value -1
$data modify entity $(eyelid_right1) start_interpolation set value -1
$data modify entity $(eye_right1) start_interpolation set value -1
$data modify entity $(jaw1) start_interpolation set value -1
$data modify entity $(head1) start_interpolation set value -1
$data modify entity $(torso1) start_interpolation set value -1
$data modify entity $(leftfrontleg1) start_interpolation set value -1
$data modify entity $(leftbackleg1) start_interpolation set value -1
$data modify entity $(rightfrontleg1) start_interpolation set value -1
$data modify entity $(rightbackleg1) start_interpolation set value -1