# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.snorlax.root] run return 0
execute on passengers if entity @s[tag=aj.snorlax.data] unless data entity @s {data:{rigHash: '41ec680cb621fe7a408827d16c0476638d7fa2c3806328753097d717b98a3629'}} on vehicle run function animated_java:snorlax/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1