# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:abra rig_hash set value '8a028ef5cb88ec9872078f49197d3b83babece4dfc5dd2d24d864c9274da20c6'
scoreboard objectives add aj.ground_idle.frame dummy