# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,0.2688f,0f,0.866f,-0.5f,-0.1375f,0f,-0.5f,-0.866f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,0.2688f,0f,0.866f,-0.5f,-0.1375f,0f,-0.5f,-0.866f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth) {transformation: [-1f,0f,0f,0f,0f,0.7071f,0.7071f,-0.3405f,0f,0.7071f,-0.7071f,0.1073f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-1f,0f,0f,-0.3875f,0f,1f,0f,-0.1875f,0f,0f,-1f,-0.3281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-1f,0f,0f,0.3875f,0f,1f,0f,-0.1875f,0f,0f,-1f,-0.3281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_beat) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.0625f,0f,0f,-1f,-0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:beat/animations/attack/zzz/frames/10_root_commands