# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,0.2687f,0f,1f,0f,-0.0795f,0f,0f,-1f,0.4135f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,0.2687f,0f,1f,0f,-0.0795f,0f,0f,-1f,0.4135f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.2825f,0f,0f,-1f,0.8333f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-0.8681f,-0.4964f,0f,-0.3875f,-0.4964f,0.8681f,0f,-0.1295f,0f,0f,-1f,0.3979f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-0.8681f,0.4964f,0f,0.3875f,0.4964f,0.8681f,0f,-0.1295f,0f,0f,-1f,0.3979f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_beat) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.0045f,0f,0f,-1f,0.476f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}