# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function ssbrc:stage/luigis_mansion/boo/tick
execute if entity @s[tag=ssbrc.entity.super_mario_bros.boo.rig.animation.idle.playing] run function ssbrc:entity/super_mario_bros/boo/rig/animations/idle/zzz/on_tick
function ssbrc:entity/super_mario_bros/boo/rig/root/zzz/0 with storage animated_java:temp entry.data.uuids_by_name