# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,0.2687f,0f,1f,0f,-0.075f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,0.2687f,0f,1f,0f,-0.075f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.278f,0f,0f,-1f,0.8573f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-0.866f,-0.5f,0f,-0.3875f,-0.5f,0.866f,0f,-0.125f,0f,0f,-1f,0.4219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-0.866f,0.5f,0f,0.3875f,0.5f,0.866f,0f,-0.125f,0f,0f,-1f,0.4219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_beat) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}