# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,0.2687f,0f,1f,0f,-0.1065f,0f,0f,-1f,0.1795f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,0.2687f,0f,1f,0f,-0.1065f,0f,0f,-1f,0.1795f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.3095f,0f,0f,-1f,0.5993f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-0.9597f,-0.281f,0f,-0.3875f,-0.281f,0.9597f,0f,-0.1565f,0f,0f,-1f,0.1639f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-0.9597f,0.281f,0f,0.3875f,0.281f,0.9597f,0f,-0.1565f,0f,0f,-1f,0.1639f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_beat) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.0315f,0f,0f,-1f,0.242f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}