# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,0.2688f,0f,1f,0f,-0.123f,0f,0f,-1f,0.0415f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,0.2688f,0f,1f,0f,-0.123f,0f,0f,-1f,0.0415f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.326f,0f,0f,-1f,0.4613f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-0.9916f,-0.1295f,0f,-0.3875f,-0.1295f,0.9916f,0f,-0.173f,0f,0f,-1f,0.0259f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-0.9916f,0.1295f,0f,0.3875f,0.1295f,0.9916f,0f,-0.173f,0f,0f,-1f,0.0259f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_beat) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.048f,0f,0f,-1f,0.104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}