# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:tyrogue rig_hash set value 'db920922726e99686e6361c964bcc1045c8d2855476769259eeb485a8974db4c'
scoreboard objectives add aj.animation_tyrogue_ground_idle.frame dummy
scoreboard objectives add aj.animation_tyrogue_ground_walk.frame dummy
scoreboard objectives add aj.animation_tyrogue_battle_idle.frame dummy
scoreboard objectives add aj.animation_tyrogue_faint.frame dummy
scoreboard objectives add aj.animation_tyrogue_sleep.frame dummy
scoreboard objectives add aj.animation_tyrogue_cry.frame dummy
scoreboard objectives add aj.animation_tyrogue_blink.frame dummy
scoreboard objectives add aj.animation_tyrogue_shoulder_right.frame dummy
scoreboard objectives add aj.animation_tyrogue_shoulder_left.frame dummy
scoreboard objectives add aj.animation_tyrogue_physical.frame dummy