# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.animation_tyrogue_ground_idle.frame
scoreboard objectives remove aj.animation_tyrogue_ground_walk.frame
scoreboard objectives remove aj.animation_tyrogue_battle_idle.frame
scoreboard objectives remove aj.animation_tyrogue_faint.frame
scoreboard objectives remove aj.animation_tyrogue_sleep.frame
scoreboard objectives remove aj.animation_tyrogue_cry.frame
scoreboard objectives remove aj.animation_tyrogue_blink.frame
scoreboard objectives remove aj.animation_tyrogue_shoulder_right.frame
scoreboard objectives remove aj.animation_tyrogue_shoulder_left.frame
scoreboard objectives remove aj.animation_tyrogue_physical.frame
tellraw @a [{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:tyrogue)'},'\n → ',{color:'green',text:'Successfully uninstalled '},{color:'yellow',text:'tyrogue'},{color:'green',text:'!'},{color:'gray',italic:true,text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.'},'\n']