# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify entity $(pupil1) start_interpolation set value -1
$data modify entity $(pupil_closed1) start_interpolation set value -1
$data modify entity $(eye1) start_interpolation set value -1
$data modify entity $(nail_head1) start_interpolation set value -1
$data modify entity $(nail_left_rotation1) start_interpolation set value -1
$data modify entity $(nail_right_rotation1) start_interpolation set value -1
$data modify entity $(magnet_left1) start_interpolation set value -1
$data modify entity $(magnet_right1) start_interpolation set value -1
$data modify entity $(body1) start_interpolation set value -1