# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=ssbrc.entity.metroid.fgii_graham.rig.animation.idle.playing] run function ssbrc:entity/metroid/fgii_graham/rig/animations/idle/zzz/on_tick
function ssbrc:entity/metroid/fgii_graham/rig/root/zzz/0 with storage animated_java:temp entry.data.uuids_by_name