# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args merge from storage animated_java:temp entry.data.locators.gas
function ssbrc:entity/pokemon/gastly/rig/zzz/at_all_locators/execute_at_transform with storage animated_java:temp args