# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_eyes) {transformation: [-1f,0f,0f,-0.0229f,0f,0.9998f,0.019f,0.3384f,0f,0.019f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,-0.0229f,0f,0.9998f,0.019f,0.3384f,0f,0.019f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tongue) {transformation: [-1f,0f,0f,-0.0229f,0f,0.9998f,0.019f,-0.0953f,0f,0.019f,-0.9998f,-0.2036f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_teeth) {transformation: [-1f,0f,0f,-0.0229f,0f,0.9998f,0.019f,-0.0953f,0f,0.019f,-0.9998f,-0.2036f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouthouter) {transformation: [-1f,0f,0f,-0.0229f,0f,0.9998f,0.019f,0.3384f,0f,0.019f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_brow) {transformation: [-1f,0f,0f,-0.0229f,0f,0.9998f,0.019f,0.3384f,0f,0.019f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth) {transformation: [-1f,0f,0f,0.4771f,0f,0.9998f,0.019f,-0.171f,0f,0.019f,-0.9998f,0.4904f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}