# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.boo.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'boo', 'function_path': 'animated_java:boo/animations/idle/pause'}
tag @s remove aj.boo.animation.idle.playing