# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$function ssbrc:game/entity/npc/pokemon/snorlax/rig/animations/sleep/zzz/frames/$(frame) with storage animated_java:temp entry.data.uuids_by_name
function ssbrc:game/entity/npc/pokemon/snorlax/rig/animations/sleep/zzz/zzz/1 with storage animated_java:temp entry.data.uuids_by_name
return 1
